### ISSUE TITLE
Ping_loop arguments list inconsistency

### ISSUE THREAD

**Issue by EvelynOtero** [Nek5000/Nek5000#104]
There are three routines "ping_loop" types in comm_mpi.f and the number of arguments is inconsistent for ping_loop1 and ping_loop2. 
It gives compilation errors with Intel compiler. 

The other question is argument list for ping_loop
 subroutine ping_loop(t1,t0,len,nloop,nodea,nodeb,nid,x1,y1,x2,y2)
which is referenced
call ping_loop (t1,t0,len,nloop,nodea,nodeb,nid,x,y,x,y)
with x1=x2 and y1=y2. Is it intentional? It seems that fortran does not recommend this type of operations.

**Comment by stgeke** [comment]
@fischer1 Can you take care of this?

**Comment by fischer1** [comment]
resolved in #123
