### ISSUE TITLE
High pass filter

### ISSUE THREAD

**Issue by negips** [Nek5000/Nek5000#108]
Do we wish to include the high-pass filter routines within V16 release?
@fischer1 ?

/Prabal

**Comment by stgeke** [comment]
Please submit a PR for this.

**Comment by stgeke** [comment]
@negips Do you want to submit a pull request for this?

**Comment by stgeke** [comment]
@pschlatt1 Are you guys still interested to see this in the next release?

**Comment by stgeke** [comment]
@pschlatt1 Are you still interested, otherwise we should close this feature request.

**Comment by pschlatt1** [comment]
I guess we can close this one for now, and reopen when it is ready.

**Comment by stgeke** [comment]
Oh I thought you guys are ready and want to submit it.
In general I think it's a very useful feature. What is missing?

**Comment by pschlatt1** [comment]
It is all there, but now it is holiday time...
Indeed, it it useful, and should definitely be there. We can also leave the issue open.
