### ISSUE TITLE
Time integration order

### ISSUE THREAD

**Issue by adampep** [Nek5000/Nek5000#109]
Nek uses two parameters to control order of time integration NAB and NBD (in TSTEP). Max value of NBD can be set by parameter(27) (general:tOrder), however max value NAB is hard-coded to be 3. For optimal forcing we have to restrict time integration to Euler and we would like to be able to control both NAB and NBD. Simple solution would be to keep current behaviour for positive values of parameter(27) and to set both parameters to NBDINP for negative one. Is it OK?

**Comment by stgeke** [comment]
Resolved in #112
