### ISSUE TITLE
Character limit for strings

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#11]
It would be great if we could increase the character limit for strings.  

Right now, the limit for many strings is 132 characters.  I've often exceeded this limit when using absolute pathnames in the SESSION.FILE.  

Is there any reason this limit can't be increased?

**Comment by maxhutch** [comment]
I would also like to see this changed.  My workflows use self-describing paths, which get long.  I've frequently had shorten case names.
