### ISSUE TITLE
wrong edge initialisation in setup_topo

### ISSUE THREAD

**Issue by adampep** [Nek5000/Nek5000#110]
Causes wrong initialisation of IEDGEF and overwriting part of ICEDG by setedge

**Comment by stgeke** [comment]
Not sure if we can close this.
Is this causing any issue? How does this "bug" manifest itself?

**Comment by adampep** [comment]
I've sent pull request for this (commit 63402bb434675a14e24bf602262a90158cc9ecea) and I guess it was merged. The problem was caused by operation going outside array bounds and setting to zero next variable. It is not really used in nek right now, but crucial for more advanced mesh operations (like amr)
