### ISSUE TITLE
modification of uzawa_gmres()

### ISSUE THREAD

**Issue by mattiasbr** [Nek5000/Nek5000#115]
Currently, the GMRES algorithm for the pressure in Pn-Pn-2 contains multiplications with operators "U^(-1)" and "L^(-1)" defined as u(i)=sqrt(b(i)) and l(i)=sqrt(binv(i)) in uzawa_gmres_split0(). The reason to have these arrays is to my understanding to have the right inner product, i.e. r^T r = f^T B f (where f is the right-hand side, r = L^(-1) res,  res=B f).

A simpler solution could be to modify the implementation and remove these arrays, by which the inner products would be carried out as
gamma(1) = sqrt(glsc3(r,r,bm2inv,ntot2))
instead of
gamma(1) = sqrt(glsc2(r,r,ntot2)).

(this possible modification was originally suggested to me by James Lottes)

**Comment by fischer1** [comment]
Thanks Mattias - can you issue a pull request for this?

**Comment by mattiasbr** [comment]
Yes, I can do that.

**Comment by stgeke** [comment]
@mattiasbr Can you please submit a pull request or should I close this issue for now.

**Comment by mattiasbr** [comment]
Sorry for being inactive, I will submit a pull request this week.

**Comment by mattiasbr** [comment]
The discussed modifications have been implemented. Currently, these only apply to uzawa_gmres() and not to hmh_gmres() used in PnPn, although similar changes probably could be made to that case as well.

In addition, LGMRES (Baker et al. 2005) has been implemented for Pn-Pn-2. The code has been tested on the 2D-flow around a cylinder (Re=100) and for this simple problem LGMRES yields no improvement over GMRES. However, for more complex problems where the iteration count can be high, LGMRES might yield a significant improvement. Therefore, this solver-option is left in the code but is inactivated.
