### ISSUE TITLE
periodic for millions of elements...

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#125]
There is a genmap issue -- fix suggested by Scicong/Elia -- that is required
for millions of elements when using periodicity.

**Comment by stgeke** [comment]
@fischer1 I believe one of your students fixed that. Can you ask him to submit a pull request with the fix.

**Comment by stgeke** [comment]
[genmap_issue.pdf](https://github.com/Nek5000/Nek5000/files/668873/genmap_issue.pdf)

**Comment by pschlatt1** [comment]
Great, thanks! I guess we can work with that now, and try to create a PR.

**Comment by emerzari** [comment]
Yes: we discussed with a while ago I believe. 

Philipp, have a fix as well very similar to this is if needed. 


>

**Comment by pschlatt1** [comment]
@emerzari: could you send it to us, then we can test it on the concrete example we have right now.

**Comment by pschlatt1** [comment]
It seems I directly pushed the simple fix to the wrong repo, sorry.
