### ISSUE TITLE
param(59) mesh deformation flag

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#126]
If a user morphs geometry in usrdat2 and does not set p59 > 0 they will not
get the right answer.

**Comment by stgeke** [comment]
Can you think of a way to set p59 automatically? I guess it is not too difficult to identify a undeformed or deformed mesh.

**Comment by fischer1** [comment]
We can set p59=1

Later, we can update the "check fast mode"

Most real codes don't get to use fast mode anyway.

(i.e., let's skip p59 and set ifdfrm=.true. ... or whatever that flag is)

________________________________

**Comment by stgeke** [comment]
Fixed in #223
