### ISSUE TITLE
mean pressure in Pn-Pn low Mach

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#128]
@ananiast should we append mean pressure to end of field file ...

**Comment by stgeke** [comment]
As discussed, it should go into the header. Will this break the Visit reader?

**Comment by pschlatt1** [comment]
apparently, this change causes problems restarting from old files without that variable. Perhaps one could fix that when reading the internal file/header.

**Comment by stgeke** [comment]
Please file a bug (issue) including some instructions how to reproduce it. Thanks.

**Comment by fischer1** [comment]
@stgeke @pschlatt1 

I just filed a bug report and posted a pointer to an exmple.

**Comment by pschlatt1** [comment]
Great! The fix is not very difficult; one should just make the "parser" of the internal file more robust. I guess we could look at it at the beginning of next week.

**Comment by stgeke** [comment]
Implemented in #134
