### ISSUE TITLE
Add Lagrangian particle solver

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#129]
transpose of interpolation matrix?

**Comment by AtzoriMarco** [comment]
Dear all, 
Do you know whether this feature will be available in the future?
Or alternatively, do you have some suggestion/indication about how to extrapolate a forcing defined on Lagrangian points in the spectral-element mesh?
Best Regards,
Marco

**Comment by stgeke** [comment]
Yes this features will be available in the near future. Probably in v18.1 which will be released the latest end of this year.

**Comment by stgeke** [comment]
Implemented in https://github.com/Nek5000/Nek5000/commit/f3295153a8c780a28f601d1ea9bd10b15895a637
