### ISSUE TITLE
Rewrite g2gi to enable restarts with a different mesh

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#130]
Instead of using our current 3-step workflow we could rewrite g2gi() to interpolate the old .fld file data onto the new mesh in one shot.

**Comment by lcarasik** [comment]
Question and potential request: Is the current g2gi() used to interpolate from one spectral order to different spectral order? Such as changing lxlt = 8 to 10? If not, can it be extended to that?

**Comment by stgeke** [comment]
This is supported already. If only p changes you don't need g2gi().

**Comment by lcarasik** [comment]
Whoops, my bad.

**Comment by stgeke** [comment]
Implemented in @ #194
