### ISSUE TITLE
Number of restarting files created and their time integration order

### ISSUE THREAD

**Issue by EvelynOtero** [Nek5000/Nek5000#131]
There should be consistency between the order of the time integration and the number of files created for restarting.

**Comment by fischer1** [comment]
What happens if you increase the time order when you restart?

**Comment by EvelynOtero** [comment]
Right now nfld_save=4 (full_restart_save(iosave), in prepost.f), so the number of files do not depend on the time integration order. For example, we want to have 2 or 3 files for a 2nd or 3rd order respectively. I will add the corresponding condition depending on the value and sign of param(27).

**Comment by fischer1** [comment]
Can you please issue a pull request and also provide an example demonstrating
the run case?

**Comment by EvelynOtero** [comment]
To answer more exactly to your previous question, the increase of the time order when you restart will not cause any problem since the names and number of files to read, is managed in our subroutine "my_full_restart" from the usr file (independently of the time order, contrary to the saving). This means that if one increases from a 2d to a 3rd order when restarting, one will first set manually in the usr file the reading  of 2 files instead of 3.

I will do a pull request providing an example yes.

**Comment by EvelynOtero** [comment]
Concerning the restart example, it already exists (cyl_restart), I will just update the usr files so there is not anymore the 4th file and I will add all the explanations in the README file.

**Comment by stgeke** [comment]
# #133

**Comment by RonRahaman** [comment]
Fixed in PR #133
