### ISSUE TITLE
Improve regression (short) tests

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#135]
Currently not tested:
- Temporal accuracy (2nd vs. 3rd order)
- CHT
- AMG (dumping AMG files, generating AMG files, AMG solve)
- History points (this will test the interpolation routines)
- Grid-to-Grid interpolation
- Solving scalars with CVODE including fluid/heat splitting
- Moving mesh
- Characteristics (with and without moving mesh)
- Restart
- Checkpoints
- ...

I guess we can recycle some of the existing examples and generate a test answer (error compared to an analytical or validated solution) automatically.

**Comment by pschlatt1** [comment]
adjoint is not tested either (both velocity and soon the temperature one)

**Comment by stgeke** [comment]
@pschlatt1 Can you provide a short_test for adjoint which we can run as regression test.

**Comment by stgeke** [comment]
https://docs.google.com/spreadsheets/d/1-ip0iWwiLyThQS_jPsDgQ8Pt62_pht1hdHuCqy84lKg/edit#gid=0
