### ISSUE TITLE
Using old-style SIZE file in a regression test

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#153]
@stgeke requested that one regression tests be run with the old-style SIZE files

**Comment by stgeke** [comment]
@RonRahaman It looks like there is no old-style SIZE file in short tests right?

**Comment by RonRahaman** [comment]
Yes, that's correct.  Thanks for reminding me of this issue!

**Comment by RonRahaman** [comment]
@stgeke, which of the test problems would you like to run with the old-style SIZE file?  Also, would you like to run the whole test problem to completion or simply check the compilation?

**Comment by stgeke** [comment]
Let's run (not just compilation) the eddy test using the old SIZE file.
