### ISSUE TITLE
Reset time at restart and use IOTIME checkpointing simultaneously

### ISSUE THREAD

**Issue by ggiannako** [Nek5000/Nek5000#157]
When restarting, the time can be reset in userchk using something like "if(istep.eq.0) time=0.0".
If one wants to restart setting t=0, but also use IOTIME for checkpointing, this requires that the variable ntdump is also set to 0 at the beginning for the checkpointing to work (see setics).

Since in general it is not advisable to play with internal common blocks it would be nice to "officially" support this feature.

**Comment by lcarasik** [comment]
I would find this of value as well.
