### ISSUE TITLE
unported path in postnek's makefile

### ISSUE THREAD

**Issue by maxhutch** [Nek5000/Nek5000#16]
[This line](https://github.com/Nek5000/nek5000/blob/develop/tools/postnek/makefile#L80) was only half ported: the blas dependency still points to nek/blas instead of core/blas

**Comment by RonRahaman** [comment]
@maxhutch, is nek5000/3rd_party/ an artifact?  Should it be deleted?

**Comment by maxhutch** [comment]
No.  That's a landing point for 3rd_party add-ons, e.g. KTH's toolbox.  It
should stay empty.

**Comment by maxhutch** [comment]
Fixed in #22
