### ISSUE TITLE
genBox requires .rea file even if output is .re2

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#161]

**Comment by stgeke** [comment]
@klheisey Can you take care of this?

**Comment by klheisey** [comment]
yep.

**Comment by klheisey** [comment]
@stgeke genbox requires a .rea file to read in the parameters and then outputs either rea or rea/re2 file with the parameters set from the input rea. Are you hoping that it could just dump out a .re2 with some sort of default .rea (or .par...?) that the user can modify as needed? Thus there is no base input file needed? The .rea file is used purely for parameter dumping/setting

**Comment by stgeke** [comment]
In case of .re2 there should be no .rea

**Comment by stgeke** [comment]
@klheisey Please can you update me on this?
