### ISSUE TITLE
HOW DO I SET TIMER=TRUE ?   THIS SHOULD BE THE DEFAULT

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#162]

**Comment by fischer1** [comment]
I set pplist "TIMER" and still am not finding my statistics..?

**Comment by fischer1** [comment]
Here is what I see for output:
        9  1.8000E-01 Write checkpoint:
       0       9 OPEN: z0.f00001

        9  1.8000E-01 done :: Write checkpoint
                              file size =     563.E-04MB
                              avg data-throughput =   142.8MB/s
                              io-nodes =     1


end of time-step loop

  
call exitt: dying ...
  
  
total elapsed time             :   2.61859E-01 sec
total solver time incl. I/O    :   2.04148E-01 sec
time/timestep                  :   2.26831E-02 sec
CPU seconds/timestep/gridpt    :   8.81239E-06 sec


real	0m0.286s
user	0m0.543s
sys	0m0.011s

**Comment by stgeke** [comment]
Just uncomment 

 

#IFPROFILING="true"

 

in makenek
