### ISSUE TITLE
makenek.inc can't detect compiler version on cray

### ISSUE THREAD

**Issue by maxhutch** [Nek5000/Nek5000#17]
On newer crays, the compiler vendor (e.g. intel, gfortran, pgi) is selected via the module programming environment.  The fortran compiler is always invoked with `ftn`, so the `case $F77comp in` line in `makenek.inc` is unable to detect the compiler vendor and often offers incorrect flags.

I don't know if there is a standard way for figuring out which backend is in use.  Maybe `module list` with some parsing logic?  I'd vote for having the option to explicitly define the compiler type in makenek, e.g.:

```
F77="ftn"
vendor="intel"
```

CC: @RonRahaman

**Comment by stgeke** [comment]
Yes, _ftn_ is just a wrapper and not a compiler. We could use `ftn -craype-verbose` to identify the selected compiler. We do something similar (_-showme_) for mpif77.

**Comment by maxhutch** [comment]
I like `ftn -craype-verbose` better than adding a new line to makenek.  I can verify that it works on XC40's.  When I switch to `PrgEnv-cray`, the first token is `ftn_driver.exe`.

@stgeke , can you repeat the `mpif77` logic?

**Comment by stgeke** [comment]
Hmm, I expected the following output

```
cc -craype-verbose ./a.out
../pgcc -tp=bulldozer -Bstatic ...
```

similar to

```
mpif77 -showme
/opt/bin/pgcc -Bstatic ...
```

**Comment by maxhutch** [comment]
The machine that I'm on (Shaheen XC40 at KAUST) has `PrgEnv-{cray, intel, gnu}`, but no `pgi`.  Here are the return values:

```
$> ftn -craype-verbose
ftn_driver.exe -hcpu=haswell ...
$> module swap PrgEnv-cray PrgEnv-intel
$> ftn -craype-verbose
ifort -xCORE-AVX2 -static ...
> module swap PrgEnv-intel PrgEnv-gnu
$> ftn -craype-verbose
gfortran -march=core-avx2 ...
```

@nicooff : Does Beskow have PGI compilers?

**Comment by nicooff** [comment]
No, Beskow has only cray, intel and GNU compilers.

**Comment by stgeke** [comment]
Ok, that's what we want. Let's add a test `$F77 -craype-verbose` similar to `-show` or `-showme`. 

```
# trying to figure out which compiler we're using
  F77ok=0
  F77comp_=`$F77 -showme 2>/dev/null 1>.tmp`
  F77comp=`cat .tmp | awk '{print $1}' | awk -F/ '{print $NF}'`
  if [ -f "`which $F77comp 2>/dev/null`" ]; then
    F77ok=1
  else
    F77comp_=`$F77 -show 2>/dev/null 1>.tmp`
    F77comp=`cat .tmp | awk '{print $1}' | awk -F/ '{print $NF}'`
    if [ -f "`which $F77comp 2>/dev/null`" ]; then
      F77ok=1
    fi
  fi

```

**Comment by maxhutch** [comment]
Want to do it?  I'm not to be trusted with bash.

**Comment by stgeke** [comment]
Sure, but I don't have access to a Cray machine.

**Comment by maxhutch** [comment]
If you open a PR, I'll test it.
