### ISSUE TITLE
BC handling

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#183]
I think we can improve the current boundary condition handling. Instead of storing the boundary conditions for all fields in the rea/re2 file we should store just the patchID for all element and faces. This enables us to modify the BCs at runtime easily and we could potentially use this information to create (complex) objects. 

To set the boundary conditions I would simply call set_bc(ifield, patchID, type, value) in usrdat2.  Here a simple example for a channel flow

```
c set BCs for velocity
set_bc(1, getPatchID('inlet'), 'v  ')
set_bc(1, getPatchID('outlet'), 'O  ')
set_bc(1, getPatchID('upperWall'), 'W  ')
set_bc(1, getPatchID('lowerWall'), 'W  ')
```

In the setup phase I establish the name/id mapping using setPathID(patchID,name). The patchID is stored internally for all faces and elements. We get this information from the rea/re2 file assuming that mesh generator provides this information.

**Comment by emerzari** [comment]
I like this option. But in addition of potentially doing this in usrdat2 could we do the assignment patch<-->boundary type in .par as well? It should be relatively easy and lightweight.

**Comment by stgeke** [comment]
Yes, this is also possible.  I believe that's what the MOAB guys did some time ago. 
We still need to think about the CHT case.

**Comment by stgeke** [comment]
Introduced setbc()
