### ISSUE TITLE
large executable ?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#188]
Any idea why nek compiles to 4 GB executable (static memory allocation), even when I delete all the f77 source code and turn off MPI ?   [  What are we linking with that is setting aside that much space? ]    This happens to be on my mac, but I think it's true elsewhere...?

**Comment by stgeke** [comment]
I noticed that too and it seems to be OSX specific. Never bothered me as the output of `SIZE` is pretty useless anyway. It's better to use the kernel function `getrusage` to get the _real_ memory usage of an application. An easy way to do this is to run `/usr/bin/time -l ./nek5000`.

**Comment by stgeke** [comment]
On Linux it is `/usr/bin/time --verbose ./nek5000`
