### ISSUE TITLE
gfortran: invoking preprocessor

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#190]
To invoke the C preprocessor for gfortran, makenek.inc sets the "-x f77-cpp-input" flag.  However, this option was replaced with the "-cpp" flag in gfortran 4.4.  Compare section 1.3, "Preprocessing and conditional compilation", in the [v4.3.6](https://gcc.gnu.org/onlinedocs/gcc-4.3.6/gfortran/Preprocessing-and-conditional-compilation.html#Preprocessing-and-conditional-compilation) and [v4.4.7](https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gfortran/Preprocessing-and-conditional-compilation.html#Preprocessing-and-conditional-compilation) manuals.  

Given that gfortran 4.4 was released in 2008, I think we should update makenek.

**Comment by stgeke** [comment]
Fixed in #223
