### ISSUE TITLE
hpts subroutines - Rewrite to prevent exit of simulation if hpts.out is already found

### ISSUE THREAD

**Issue by lcarasik** [Nek5000/Nek5000#198]
Currently, Nek will exit or "crash" if a hpts.out is found when a new run has been started. This can be quite cumbersome due to Nek continuing to hold up resources on certain systems without properly exiting. In general, I feel it would be a nice modification for nek to just overwrite the old hpts.out file it finds instead of exiting or crashing. 

I can try and figure out how to do this, but it will be awhile till I can look into it. I feel this might be a feature the user community would appreciate though.

**Comment by fischer1** [comment]
The right thing to do here is to open a file with name:

session.hpts_out

________________________________

**Comment by stgeke** [comment]
It was designed as a safety feature to prevent overwriting, similar to the existing .sch file logic. I general I prefer the "do-what-I-say" mode instead some hidden magic trying to prevent a user mistake. 



I agree with Paul, we should change the filename.

**Comment by lcarasik** [comment]
I understand both of your perspectives and just for clarity, session is case name?

**Comment by fischer1** [comment]
Hi Lane,

yes...

blah.rea
blah.hpts_out
blah.hpts_in

etc.


________________________________

**Comment by lcarasik** [comment]
Ah thank you, just making sure.

**Comment by lcarasik** [comment]
Was this issue closed due to inactivity? Or did I misunderstand the previous discussion that this feature already exists within the code?

EDIT: I see this has been addressed with the recent pull. Thanks for adding the feature Stefan!

**Comment by GerritBotha** [comment]
Hi Neks

I am following the advice Paul gave to Lane regarding the hpts. I renamed my probe points file to "case.hpts_in", where "case=2s_2.0d" and added call hpts() to my usrchk. When the code is run my logfile as the following error right after my initial conditions from a restart file is loaded.

 call userchk
 dump history points
 reading history points
 Cannot open history file in subroutine hpts()
  
call exitt: dying ...

I have tried renaming the hpts input file to that of the legacy format, but no luck.

Thanks!

**Comment by lcarasik** [comment]
Hey Gerrit, 

What version of history points are you using? If you're using the old version, you can only use a file called hpts.in for it to work. 

If you are using the new version of history points, I recommend looking at the hemi example to see how to do the new implementation.

**Comment by GerritBotha** [comment]
Hey Lane 

I downloaded the github verson about a month ago. Tried the hpts.in format, but did not work either. I`ll look at the example.

Thanks!

**Comment by lcarasik** [comment]
Best of luck, if there is an easier way to show off the new implementation, please consider writing a short tutorial on it!

**Comment by GerritBotha** [comment]
I looked at the example and it seems that they are doing particle tracking. I require a line interpolation of the velocity field at certain locations

**Comment by lcarasik** [comment]
Ah my mistake, I don't remember where else you can find it at the moment. But this link should get you started, https://github.com/Nek5000/Nek5000/pull/223/commits/110f412b55ea847b4b8593da57fe258cedca4a8c

In principle, it should work the same, but I'm not sure the exact syntax.

Try, casename.his

**Comment by GerritBotha** [comment]
I tried all the above variations. When using casename.his gets renamed to casename.his1, but still crashes after loading the initial values.

**Comment by lcarasik** [comment]
How does it crash? What is the error? Same as above?

**Comment by stgeke** [comment]
Please update to a more recent version. All this was fixed some time ago.

On 19 Oct 2017, at 06:08, Lane Carasik <notifications@github.com <mailto:notifications@github.com> > wrote:

How does it crash? What is the error? Same as above?

**Comment by stgeke** [comment]
If there is still a problem please create a new issue instead file of using this issue which is closed.

On 19 Oct 2017, at 08:30, Stefan K. <notifications@github.com <mailto:notifications@github.com> > wrote:

Please update to a more recent version. All this was fixed some time ago.

On 19 Oct 2017, at 06:08, Lane Carasik <notifications@github.com <mailto:notifications@github.com> <mailto:notifications@github.com <mailto:notifications@github.com> > > wrote:

How does it crash? What is the error? Same as above?
