### ISSUE TITLE
Mesh Quality Metrics

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#199]
I think it would be useful to compute/print some mesh quality metrics during the initialization phase. This way the user gets a warning if a metric is outside the acceptable range. 

https://cubit.sandia.gov/public/14.0/help_manual/WebHelp/mesh_generation/mesh_quality_assessment/hexahedral_metrics.htm

**Comment by pschlatt1** [comment]
I think that would be a great feature. However... do we know what the acceptable range for Nek/SEM is?

**Comment by stgeke** [comment]
Actually I don't know.
To make it even more difficult:  Some of them are related to accuracy and/or performance.

**Comment by pschlatt1** [comment]
True! In any case, I agree having some numbers listed is very good in any case.

**Comment by kmittal2** [comment]
I can look into this... We already use a metric for mesh-optimization. I plan on adding more metrics to it, and I guess those same metrics can be evaluated at the beginning of a run. We should also be able to use these metrics as triggers for automatic mesh optimization of deforming meshes.

**Comment by stgeke** [comment]
Closing this for now, two are implemented in https://github.com/Nek5000/Nek5000/commit/c793325a1438c5936b3eea118150ce7653e325e7
