### ISSUE TITLE
outsource jl code as a library

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#200]
The jl-code started as a build-in component of Nek5000. To make it more visible/useable for other software projects we consider to release it as a separate library. This requires some refactoring of the current jl-code and the Nek5000 build system. 

btw: This will speedup the compilation by >50% on most systems as we don't have to recompile the jl-code every nek build.

**Comment by RonRahaman** [comment]
When we do this, I think we should take the opportunity to provide a standardized build system for libjl.  In the past, I developed both a CMake and an autotools build system for Nek5000, including, and they're both quite nice.

**Comment by stgeke** [comment]
Currently we compile the jl-code with the AMG_DUMP preprocessor symbol to dump some setup files. That's something we want to avoid if we consider jl as a true library. 

@jlottes Can you think of an easy fix?

**Comment by stgeke** [comment]
Similar for XXT or AMG. The user should be able to make this choice at runtime.

**Comment by stgeke** [comment]
#208 eliminates `AMG_DUMP` and dumps automatically if the AMG solver input files are not found. To use the XXT or AMG solver we could link against a different library. This will avoid recompiling the jl library.

**Comment by jlottes** [comment]
That sounds like a fine solution. It would also be trivial to rename the
main XXT and AMG solver routines and have a single entry point that
dispatches to either based on an argument.

**Comment by stgeke** [comment]
Implemented in #258
