### ISSUE TITLE
eddy_neknek problem with Hmholtz

### ISSUE THREAD

**Issue by makavakh** [Nek5000/Nek5000#204]
There is a problem with the Helmholtz solve in the eddy_neknek example that needs to be looked at. Here is a snippet from the logfile:

> Project velx                  NaN          NaN          NaN   1   1
> Error Hmholtz velx     100          NaN          NaN   1.0000E-12
> proj_ortho:    1   2 velx   Detect rank deficiency:         NaN         NaN
> Project vely                  NaN          NaN          NaN   1   1

**Comment by stgeke** [comment]
Will be fixed with #252
