### ISSUE TITLE
Fast OIFS/Characteristics advection operator

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#207]
We may want to think about tuning our current OIFS/Characteristics advection operator implementation. Based on my experience, we spend more than 50% of the total computational time in this operator (using torder=2). Hot kernels (consuming 90%) for this operator are

- local_grad3
- specmpn

which are essentially MxMs. 

Not sure if a vector version (computing all three components of the advection operator) could be helpful.

**Comment by fischer1** [comment]
It looks to me like we might get 2x performance by tuning this.
I'll see if I can get some help from one of my students.

Paul

________________________________

**Comment by stgeke** [comment]
Replaced by #406
