### ISSUE TITLE
Short tests: legacy SIZE file does not have declarations

### ISSUE THREAD

**Issue by negips** [Nek5000/Nek5000#216]
One of my pull requests is failing a test. It seems the reason is because the legacy SIZE file does not have declarations. So when I include implicit none is the code, it gives me errors regarding undeclared variables (in the SIZE) file. Could the legacy SIZE be updated to include declarations?

**Comment by stgeke** [comment]
This is a feature not a bug as we want to continue to support the old SIZE files.
