### ISSUE TITLE
Why does 3rd order restart need 4 files?

### ISSUE THREAD

**Issue by maxhutch** [Nek5000/Nek5000#23]
Nek5000 typically uses a 3rd order time-stepper (BDF/EX3).  To do a full restart, which avoids a drop in integration order, you'd expect to need 3 checkpoint frames.  However, in Nek5000 you need 4.  Why?

CC: @oanaoana

**Comment by pschlatt1** [comment]
I support this issue as a very important issue to be resolved, in particular for large runs for which quite some saving (time and storage) could be achieved at zero cost. If anybody has a hint/suspicion it would be great!

**Comment by stgeke** [comment]
@fischer1 Any idea?

**Comment by fischer1** [comment]
Because it works and 3 doesn't, last I checked.

Paul

**Comment by maxhutch** [comment]
NekBox (pn-pn only) is able to do full BDF3/EX3 restarts with only 3
checkpoints.  It checks reproducibility to 9 digits.  The math in NekBox
and Nek5000 should be the same so, in the absence of a mathematical reason
for needing 4, NekBox suggests Nek5000 should be able to get away with 3.
The difference is likely in the restart implementation somewhere, as it
differs the most between Nek5000 and NekBox.

For reference, here is the [NekBox restart driver](https://github.com/maxhutch/NekBox/blob/develop/core/io_mod.F90#L21)

**Comment by fischer1** [comment]
Why only 9 digits?

**Comment by maxhutch** [comment]
9 because that's my default "within iterative tolerances" check.  I just
went back and all of the printed solution values are the same for all the
printed digits.  The trailing digit or two in the norm of the residual is
different in a few places, but that's ~1e-16.

**Comment by stgeke** [comment]
#100

**Comment by stgeke** [comment]
Resolved in #113
