### ISSUE TITLE
Alignment of output in the logfile

### ISSUE THREAD

**Issue by lcarasik** [Nek5000/Nek5000#24]
The logfile provides us with a large amount of useful information but isn't aligned to make it easier to read. I've previously discussed this with @dshaver-ANL and @maxhutch and it seems like it should be a reasonable "improvement" to the code. Further, utilizing @dshaver-ANL's help the following fortran files which specific lines called out are below:

hmholtz.f - line 829-832 - Format Statements
gmres.f - line 522-525 - Format Statements
subs1.f - line 166-171 - Format Statements

![unaligned_logfile](https://cloud.githubusercontent.com/assets/19592378/16810220/c1291122-48e8-11e6-937a-6a42cf928ad5.png)

Specially, can the output be aligned vertically to the "iteration number"?

**Comment by maxhutch** [comment]
I think this would be great!  By "iteration number" do you mean "[time-]step number", e.g. 14 and 15 in this case?

**Comment by lcarasik** [comment]
Wonderful! And yes that was an error on my part, I meant the time-step number.

**Comment by dshaver14** [comment]
Something like this would be ideal, where the format string is (4x,i7,a21,i4,(N)ES13.4).  Or anything that makes it easy to see whichever number I care most about as it flies by with the time step.

![image](https://cloud.githubusercontent.com/assets/20442860/17373461/e3fe154a-596d-11e6-8d96-f8fa127dc9b0.png)

**Comment by RonRahaman** [comment]
This looks great to me.  Please feelfree to submit a pull request.

**Comment by stgeke** [comment]
I'll submit a PR soon fixing this issue among other things.

**Comment by maxhutch** [comment]
@stgeke keep the PRs as atomic as logically reasonable
