### ISSUE TITLE
.f0000# file read error

### ISSUE THREAD

**Issue by LambertFick** [Nek5000/Nek5000#241]
Hello all,

We seem to be having an issue with loading .f0000# files created using previous versions of the code on the ANL BG/Q machines when using the latest master version. I checked the previous issues, and it seem something similar was fixed earlier:

Issue: https://github.com/Nek5000/Nek5000/issues/154

Ron mentioned that the regressions are not normally run on the BG/Q machines, so I just wanted to highlight the problem.

I've been able to successfully run some post-processing scripts using an SVN version of the code, but when I switch to the latest master version it hangs when trying to read the field once setics is called.

Please let me know what info, if any, we can provide to help get the issue resolved.

Lambert

**Comment by pschlatt1** [comment]
we had some issues with big endian restart files from IBM machines at some point; I think it was in the mesh part...? Is there some more info from the output file?

**Comment by LambertFick** [comment]
Attached is a logfile from Jon Lai (fellow student at TAMU), who is running into the same issue.

[logfile.txt](https://github.com/Nek5000/Nek5000/files/873667/logfile.txt)

**Comment by stgeke** [comment]
Can you please try again with the latest master?

**Comment by LambertFick** [comment]
I re-downloaded and tested, seems to be working on two cases of mine now.

Jon Lai also just confirmed that his runs are working now.

Sorry for the false alarm, as of my tests last week it didn't seem to be working, and the version Jon was using was a couple of weeks old.

Lambert
