### ISSUE TITLE
Unable to read data from outpost

### ISSUE THREAD

**Issue by jklai12** [Nek5000/Nek5000#242]
After updating to the newest master version, I am having difficulty reading field files from outpost (in both VisIt and Nek).

In the attached logfiles, I made a test where I used "call outpost(vx,vy,vz,pr,t,'') " and then "call exitt" after a few time steps.
[logfile_outpost.txt](https://github.com/Nek5000/Nek5000/files/876596/logfile_outpost.txt)

Then, I tried reading the field file from outpost as the restart field for another run. It gives a "NONSTD HDR, parse_hdr, abort." error and then proceeds with ICs from useric. Could anybody help me with why outpost is writing an unreadable file?
[logfile_readingdata.txt](https://github.com/Nek5000/Nek5000/files/876603/logfile_readingdata.txt)

Thank you

**Comment by stgeke** [comment]
Please send the output of `head init0.f00002 | strings`
 
-----Original message-----

**Comment by jklai12** [comment]
head init0.f00002 | strings does not give an output (whereas init0.f00001 does).

This means there is no header from the outpost field. Am I calling the outpost subroutine incorrectly?

**Comment by stgeke** [comment]
strange - outpost works for me

**Comment by jklai12** [comment]
Looks like changing the compiler fixed this problem.

On Mira (a Blue Gene/Q system), using:
F77="mpixlf77"
CC="mpixlc"
instead of 
F77="mpif77"
CC="mpicc"
worked
