### ISSUE TITLE
How to use interpolation with the new implementation?

### ISSUE THREAD

**Issue by lcarasik** [Nek5000/Nek5000#243]
The recent changes to master nek branch has broken several users' routines involving spectral interpolation. Can someone please provide a proper explanation on what specific routines that are called were changed and how to re-implement them? Such as, if I previously used intpts_setup(tolin, ihandle) what do I replace it with?

**Comment by stgeke** [comment]
Typically I would use the findpts routines directly. If you look for a simple wrapper just check intp.f
 
-----Original message-----

**Comment by lcarasik** [comment]
Can you please provide an example of how you changed the routines? What is needed to ensure they are re-implemented properly?

**Comment by stgeke** [comment]
There will be one in NekExamples (hemi) but we haven't updated it yet. It will be available one there is a official release. 
Just look at intp.f - the interface is pretty much the same as the old one. 
 
 
-----Original message-----

**Comment by lcarasik** [comment]
I really recommend you include the example in Nek Examples WHEN you update the code. Also, why is an explanation (i.e. how to properly account for changes in user code) of the changes not included with major updates like this?

**Comment by stgeke** [comment]
See Backward-Incompatible Changes

On 28 Mar 2017, at 20:23, Lane Carasik <notifications@github.com <mailto:notifications@github.com> > wrote:

I really recommend you include the example in Nek Examples WHEN you update the code. Also, why is an explanation of the changes not included with major updates like this?

**Comment by lcarasik** [comment]
This is how you lose users.

**Comment by stgeke** [comment]
I am sorry that your not satisfied with our performance. We try hard to keep you (the users) happy. We only break the backward comparability is there is no good alternative. The only thing we can do in this case is document the change.

I agree an updated NekExample should be part of the change. I am afraid sometimes time is pressing and there is no time to do the "right" thing.

If you look for stability use the latest (but old) SVN version or the release once it is available.


On 28 Mar 2017, at 20:28, Lane Carasik <notifications@github.com <mailto:notifications@github.com> > wrote:

This is how you lose users.

**Comment by lcarasik** [comment]
> I am sorry that your not satisfied with our performance. We try hard to keep you (the users) happy. We only break the backward comparability is there is no good alternative. The only thing we can do in this case is document the change.

But the change wasn't documented. Yes the files were changed and can be seen on github, but the functionality was striped out of it's normal usage. There isn't even a description on the specific PR about what was changed and why. The user forum is a dumpster fire and is barely searchable.

> I agree an updated NekExample should be part of the change. I am afraid sometimes time is pressing and there is no time to do the "right" thing.

Then the changes should be done in a fork and not to the master branch.

The point is, NekExamples only is so useful without any explanations with the NekExamples. There should be a proper change in the manual on how to handle the changes or in general how to use the code.

> If you look for stability use the latest (but old) SVN version or the release once it is available.

When is the last time this has been updated? The last I've heard is SVN hasn't been updated for quite a significant period of time and won't be updated in the future. The changes between SVN versions do not seem to be discussed.

-----

I want to code to be successful and to be used by a broad community. I can't justify encouraging new users (especially industrial users) when the code changes aren't documented, the verification suite is lacking, and the major developers make code changes and do not tell anyone how to accommodate for it.

**Comment by stgeke** [comment]
It's good that you care about the project. Are you willing to help us and update the hemi example and the user guide? We are looking for more collaborators.

**Comment by emerzari** [comment]
Thanks Lane,

These are very good points and the move to git was meant to facilitate better practices: more documentation and explanation about changes. That, as you point out was not easy to do with SVN.

Obviously we are not there yet. The plan is to get there with a release. But we are striving for it and hopefully we will get there soon. Your help with the guide and pointing out issues is very much appreciated.

As Stefan mentioned, If you can spare anytime to help with hemi or other examples we would very much like that.

**Comment by lcarasik** [comment]
@stgeke  Of course, I'm happy to help out. I've been wanting to update the user guide for awhile.

**Comment by stgeke** [comment]
See `hemi` example.
