### ISSUE TITLE
How to set NEKNEK flags in SIZE  (SIZE.template)

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#249]
SIZE.template file has the following parameters:

      parameter (nsessmax=1,nmaxl=1,nfldmax=1,nmaxcom=1) ! multimesh parameters

But nowhere in the code is there a clue of how they should be set when someone
wants to run neknek.
(I've asked Ketan to look at this.)

**Comment by RonRahaman** [comment]
How do these correspond to the variables set in SESSION.NAME by the bin/neknek script?

**Comment by stgeke** [comment]
I think most of these parameters will be obsolete with the refactored NEKNEK implementation and the new `SIZE.template`.
