### ISSUE TITLE
amg files need a name (e.g., for neknek)

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#260]
When running neknek, we have more than one set of case files.

For amg, we'll need to name the amg files --

I suggest:

blah_amg.dat
blah_amg_W.dat
etc.

If the code doesn't find them with the "blah_" prefix it would look for files without
the prefix.

Here, "blah" would be the session name.

This will allow use of AMG + neknek.

Paul

**Comment by stgeke** [comment]
How would `gislib` (here we are reading/writing the AMG files) know our session name? Any chance to run the different neknek session in different directories?

**Comment by fischer1** [comment]
Running in different directories is a pain for the user, inflicted a 100 times a day, several days per week.

**Comment by stgeke** [comment]
I don't think there is a portable way to pass strings between Fortran and C. Any other ideas how we tell `gslib` what files to read?
