### ISSUE TITLE
valid map/re2 pair

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#273]
We may want to add a re2-checksum to our map file. This ensure that the map and re2 are consistent.

**Comment by emerzari** [comment]
This would be useful for users. It is a common user error, once you change the mesh to forget to redo genmap. The code will output several error messages as a result (e.g., negative jacobians) but it may take the user a while to figure out the actual error.

**Comment by stgeke** [comment]
Not required if #366 is implemented
