### ISSUE TITLE
Free Surface Flow with PnPn

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#274]
Seems to be broken as the pressure solve doesn't converge.

**Comment by fischer1** [comment]
I've never known PnPn to support free surface?

**Comment by stgeke** [comment]
Ok in this case we should print at least an error message saying `MS` BCs are not supported with PnPn. We should also remove the PnPn runs for all free surface flow examples on Jenkins.

**Comment by stgeke** [comment]
@fischer1 Any news?

**Comment by stgeke** [comment]
Duplicate to https://github.com/Nek5000/Nek5000/issues/421
