### ISSUE TITLE
move short tests into `short_tests`

### ISSUE THREAD

**Issue by maxhutch** [Nek5000/Nek5000#28]
We planned on moving the tests that don't have large input files into `short_tests`.  This strikes a balance between including some tests and examples with the code while also keeping checkout lightweight.  Here's a list of some short tests.  In most cases, the mesh information needs to be stripped from the rea file and the map file removed.
- [ ] eddy 
- [ ] benard

**Comment by stgeke** [comment]
I think we don't need all three as they exercise all the same parts of the code. To obtain a good code coverage, we need to add other tests.

**Comment by maxhutch** [comment]
Benard and eddy are different (forced vs not; scalar vs not).  We can remove kovasznay.  Do you have suggestions for additions (from `nek_examples`)?

**Comment by stgeke** [comment]
For me a short_test is:
- serial runtime < 1-2min
- size < 500K
- workflow and test answer is fully automated
- improves code (feature) coverage

The following existing nek/examples come to mind:
- eddy
- kov
- benard
- lowMach
- var_vis
- mv_cyl
- axi
  May be there are more, but I guess that¹s a good starting point. 

@RonRahaman What needs to be done to run all these tests for every push?

**Comment by RonRahaman** [comment]
@stgeke, here is what needs to be done.  I'll start on all of these today:
- [ ] Copy those examples from NekExamples into Nek5000/short_tests
- [ ] Copy the NekTests.py script and libraries from NekExamples to Nek5000/short_tests
- [ ] Edit the .travis.yml file to run these tests in Travis

This will allow those tests to be run for every pull request.  

You can also set up your own Travis account to run the tests every time you push to your fork.  See steps 1 and 2 here: https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A

**Comment by RonRahaman** [comment]
@stgeke, which benard test cases did you want to do?  There are several .rea files we can run

**Comment by RonRahaman** [comment]
Closed in #41
