### ISSUE TITLE
why opgrad instead of gradm1 for PnPn?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#299]
For PnPn, I don't see why we don't use an equivalent of gradm1(), instead of opgrad().

gradm1() will be literally 10x faster.   Opgrad makes 27 mxm calls, gradm1 makes only 3.

I see in opgrad the following code commented out, but I don't know why it is commented
out.

The same will be true for multd().   In recent timings that I saw, this savings would yield a 9% reduction in run time.

c        if (ifsplit) then
c
c             call mxm  (dxm12,nx2,x(1,e),nx1,dx(1,e),nyz1)
c             call col2 (dx(1,e),rm2(1,e),nxyz2)
c             i1=1
c             i2=1
c             do iz=1,nz1
c                call mxm (x(1,e),nx2,dytm12,ny1,ta1(i2),ny2)
c                i1=i1+n1
c                i2=i2+n2
c             enddo
c             call addcol3 (dx(1,e),ta1,sm2(1,e),nxyz2)
c             call mxm (x(1,e),nxy2,dztm12,nz1,ta1,nz2)
c             call addcol3 (dx(1,e),ta1,tm2(1,e),nxyz2)

c           else ! PN - PN-2

             call mxm (dxm12,nx2,x(1,e),nx1,ta1,nyz1)
             i1=1
             i2=1
             do iz=1,nz1
               call mxm (ta1(i1),nx2,iytm12,ny1,ta2(i2),ny2)
               i1=i1+n1
               i2=i2+n2

**Comment by ananiast** [comment]
opgrad is called in plan4 and drive2, and only for ifsplit=true (Pn-Pn). In the beginning of the routine though, unless it is an axisymmetric case, it calls wgradm1 which is very similar to gradm1. multd is only called for axisymmetric problems.
