### ISSUE TITLE
HOW DO I TURN OF IFMPI IN MAKENEK ???

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#300]

**Comment by fischer1** [comment]
Never mind... I found it...

**Comment by fischer1** [comment]
HOWEVER,

Where do I put the flags   G='Ktrap=fp, mcmodel=medium'  etc ??

**Comment by fischer1** [comment]
OK... found that one too ...

**Comment by stgeke** [comment]
In FFLAGS

On 1 Jun 2017, at 22:36, fischer1 <notifications@github.com <mailto:notifications@github.com> > wrote:

HOWEVER,

Where do I put the flags G='Ktrap=fp, mcmodel=medium' etc ??
