### ISSUE TITLE
legacy .usr template w/o "implicit none"

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#316]
@fischer1 requested that we include a legacy .usr file without "implicit none"

**Comment by stgeke** [comment]
That's already in place e.g. `short_test/eddy/eddy_uv.usr`

**Comment by fischer1** [comment]
Can we have a  /core/zero.usr that is with out implicit none?

I use that file all the time...

**Comment by fischer1** [comment]
To be clear, I'd like zero.usr in /core to be without implicit none.

We can zero_none.usr be with implicit none.
