### ISSUE TITLE
Generate .rea and .re2 in Nek5000

### ISSUE THREAD

**Issue by thilinarmtb** [Nek5000/Nek5000#326]
Looks like genbox does not generate both .rea + .re2 when the dimension
in box file is set to negative. I have to use reatore2 to convert from .rea to 
.rea + .re2. 

Is there a workaround other than just using reatore2? What is the motivation
behind this change?

Thanks in advance !!

**Comment by stgeke** [comment]
This was introduced with the new `.par` replacing the `.rea` file . In this format the mesh and the solver runtime parameters are stored in different files. The legacy `.rea` stores everything in one file. I recommend to use either `.par & .re2` or the good old `.rea`.

**Comment by thilinarmtb** [comment]
Hi Stefan, 

Thank you for the reply. How do I create a ".par" file and ".re2" file using newer genbox?

**Comment by stgeke** [comment]
`genbox` is a meshing tool so it does not generate a `.par` file. Currently there is no tool to generate a `.par` file. Just start from e.g. `short_tests/ethier` and modify it to your needs.

**Comment by thilinarmtb** [comment]
Thanks for the reply Stefan !!

I will give it a try.
