### ISSUE TITLE
Nek5000 now require to use AMG for larger problem sizes

### ISSUE THREAD

**Issue by thilinarmtb** [Nek5000/Nek5000#327]
Looks like Nek5000 now require to use AMG for larger problem sizes (say, 2^19)
and stop the run if AMG is not used for these sizes. Is there a way to stop this
behavior and keep running Nek5000 normally for larger meshes?

Thanks in advance !!

**Comment by stgeke** [comment]
The code limits the XXT usage to 350'000 elements otherwise the factorization would take a long time. We may want to increase this number to 500'000.

**Comment by thilinarmtb** [comment]
Hi Stefan, Thank you very much for the reply !! 

Looks like I can get around this by setting p040=1.

I am closing this issue.
