### ISSUE TITLE
License compatibility

### ISSUE THREAD

**Issue by kent0** [Nek5000/Nek5000#335]
Nek5000 is BSD licensed, but a utility in /bin called git-hub is GPLv3. From my understanding of how licensing works, that should make Nek5000 GPLv3 as well. If this is the case, LICENSE needs to be updated or git-hub needs to be replaced with BSD licensed code.

**Comment by stgeke** [comment]
I don't this this is an issues as bin/git-hub is an third party program which is independent of Nek5000. 

On 23 Jun 2017, at 16:27, Kento Kaneko <notifications@github.com <mailto:notifications@github.com> > wrote:

Nek5000 is BSD licensed, but a utility in /bin called git-hub is GPLv3. From my understanding of how licensing works, that should make Nek5000 GPLv3 as well. If this is the case, LICENSE needs to be updated or git-hub needs to be replaced with BSD licensed code.

**Comment by kent0** [comment]
Ok, thank you for the clarification
