### ISSUE TITLE
how to download nek5000 examples ?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#340]
When I google "nek5000 examples" , it takes me here:

https://nek5000.mcs.anl.gov/nek-examples/

when I get there, there is no button or instruction on how to grab the git repository

??

**Comment by kent0** [comment]
@fischer1 You can download it by running the following command:

`git clone https://github.com/Nek5000/NekExamples`

**Comment by fischer1** [comment]
Thanks - Yes I eventually found the DOWNLOAD button.

I still think the page needs to be changed because, as it stands, it's obvious how to download the documentation, but not the Examples.   

Even after clicking the DOWNLOAD tab, the next page does not clearly tell how to get the Examples.

This is wrong.
