### ISSUE TITLE
Continue to support generating `map` files from an `re2`?

### ISSUE THREAD

**Issue by person142** [Nek5000/Nek5000#347]
It seems that with the changes in https://github.com/Nek5000/Nek5000/commit/2d1b8db3fbd1714d57f94ce368c0dff0fed24d18 a `ma2` file will always be generated from an `re2` file with `genmap`. (Perhaps I am misunderstanding, in which case my apologies.)

In NekCEM we use the Nek5000 tools to generate rea/re2/map files, but we haven't ported the upstream changes to allow us to use `ma2` files, so using `genmap` built with the master branch of Nek5000 on an `re2` file doesn't work. Is it possible to continue supporting the generation of `map` files from `re2` files?

**Comment by stgeke** [comment]
How about having your own tools in NekCEM. This will ensure that you are always compatible.

On 23 Jul 2017, at 22:21, Josh Wilson <notifications@github.com <mailto:notifications@github.com> > wrote:

It seems that with the changes in 2d1b8db a ma2 file will always be generated from an re2 file with genmap. (Perhaps I am misunderstanding, in which case my apologies.)

In NekCEM we use the Nek5000 tools to generate rea/re2/map files, but we haven't ported the upstream changes to allow us to use ma2 files, so using genmap built with the master branch of Nek5000 on an re2 file doesn't work. Is it possible to continue supporting the generation of map files from re2 files?
