### ISSUE TITLE
P20 & old .rea files

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#348]
It appears that param(20) currently triggers some tolerance behavior in hmholtz.f

However, it was pointed out to me today that there are some historic .rea files floating around from when param(20) used to store the integer  "NORDER", which could be positive or negative.

These files apparently end up with unexpected behavior...

**Comment by emerzari** [comment]
Yes.

I believe this was done by Stefan a while ago to manipulate the tolerance of the temperature separate from the velocity.

 I also pointed pointed out the inconsistency with legacy .rea.

Elia
________________________________

**Comment by fischer1** [comment]
Here is a suggestion ---

Let's ignore p20 as set in any .rea file, but allow users to set p20 in the .usr file (only).

This is similar to the way p99 behaves and to p66/67.

Also, on a related topic, I think we're going to need to be able to explicitly control tolerances for all fields, including the unknown mesh velocity when using ALE+elasticity solver.

Maybe a "tolfld" vector ?

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/7d707a5f3078396d283304994958e383779cfe4b
