### ISSUE TITLE
Dimension of ifqinp causes bug in 2D

### ISSUE THREAD

**Issue by nicooff** [Nek5000/Nek5000#352]
The array `ifqinp(6,lelv)` (in GEOM), which decides if boundary values need to be projected normally to the surface, is initialized to false like this in subroutine `setlog` (bdry.f):

```
NFACE  = 2*NDIM
NMXV   = NFACE*NELV
...
CALL LFALSE (IFQINP,NMXV)
```

In 2D, it means that some elements are not initialized since memory is not contiguous. This caused some issues for one of my case and my fix was to declare the array as `ifqinp(2*ldim,lelv)`.

Same goes with array `ifeppm` even though it does not seem to be used anywhere (should it be deleted?).

**Comment by stgeke** [comment]
#353
