### ISSUE TITLE
nekqsub still missing?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#354]
It's difficult to tell users how to run in a batch queuing system if we have no example in Nek5000/bin, e.g., something like:

rm *cobalt*log
rm logfile
rm *output
rm *error

echo  "#!/bin/bash"                                              > $1.batch
echo  "#COBALT  -q gpu_mules"                                   >> $1.batch
echo  "#COBALT  -n 1"                                           >> $1.batch
echo  "#COBALT  -t 00:10:00"                                    >> $1.batch
echo  cd `pwd`                                                  >> $1.batch
echo  "echo" $1      ">"  SESSION.NAME                          >> $1.batch
echo  "echo \`pwd\`'/' >> SESSION.NAME"                         >> $1.batch
echo  rm -f  $1.his1                                            >> $1.batch
echo  rm -f  $1.sch1                                            >> $1.batch
echo  rm -f  $1.log1                                            >> $1.batch
echo  mv $1.log $1.log1                                         >> $1.batch
echo  mv $1.his $1.his1                                         >> $1.batch
echo  mv $1.sch $1.sch1                                         >> $1.batch
echo  rm -f logfile                                             >> $1.batch
echo  rm -f ioinfo                                              >> $1.batch
echo  sleep 5                                                   >> $1.batch
echo  "./nek5000 >&"    $1.log                            >> $1.batch
echo  sleep 5                                                   >> $1.batch
echo  ln $1.log logfile                                         >> $1.batch
echo  "exit 0;"                                                 >> $1.batch
chmod +x $1.batch
qsub  $1.batch
sleep 3
qstat

**Comment by stgeke** [comment]
Queueing system use different workflows to launch a job. I doubt it that we can come up with a good template which is helpful for the user. A good starting point is `nekmpi`.

**Comment by stgeke** [comment]
I agree, instead we should use `luparam` in the code and set it to 10 in `INPUT`.

**Comment by fischer1** [comment]
I've been running on batch systems for decades and I always end up using something derived from the above or its ancestor.

I think we should be able to point users to some kind of template.  [ I just grabbed the COBALT one, but a more generic one would be based on nqs or whatever. ]
