### ISSUE TITLE
CylRestart_P fails because of possible gslib problem 

### ISSUE THREAD

**Issue by adampep** [Nek5000/Nek5000#361]
After a number of tests and digging into the code it seems I've found the source of the problem with new projection scheme in CylRestart_P test. I focused on non-stress formulation for pn-pn and pn-pn-2. For pn-pn both pressure and velocity projection use the same routines, however pn-pn-2 shares with pn-pn only velocity projection routines. The problem appears for parallel runs using velocity projection only and it is completely random. Pressure projection is fine even though for pn-pn is uses the same routines as velocity. I took me a while to realize that random behaviour of velocity projection is correlated with  the method picked up for all-to-all communication by the gs_setup in the first call to setupds inside setup_topo (it she first gs_setup call in nek). In my case gs_setup randomly chooses between gs_pairwise (test fails) and gs_crystal_router (test succeeds). To test this I modified default method in fgs_setup (gs.c) and I've got for :

const sint method = gs_auto                 - random behavior

const sint method = gs_crystal_router  - no failures

const sint method = gs_pairwise           - only failures

**Comment by fischer1** [comment]
This issue appears to be resolved with my lastest navier4.f

**Comment by adampep** [comment]
Yes. I've just checked the file Paul sent me (not in repository yet) and it works. However, the question about gs remains open. What Paul changed is operations order. Correct me if I'm wrong. Old version (probably to minimize communication) first performs local projection on existing base, next calls global sum (only once) and finally subtracts contributions from different base vectors. Paul's version performs global projections and subtract vector directly before projecting next one. Both methods should give the same if the base is orthonormal. For not really orthogonal base Paul's method is much more stable, because subtracting vector directly one takes care of possible "overlap" of base vectors. Base orthogonality is ensured in proj_ortho and this routine remains unchanged. So the question now is: Why with crystal router the base seem to be orthogonal (old code version does not bow up), and with pairwise it is not (old code blows up)? Both crystal router and pairwise add some noise, but only the noise from pairwise seems to cause trouble.

**Comment by fischer1** [comment]
Hi Adam,

I dug into this quite carefully and am fairly convinced that this is a numerical stability issue where one version of gslib produces slightly (e.g., at machine round-off level) different results than the other.  The old version was based on classical Gram-Schmidt, the new one is modified Gram-Schmidt.

Your question is a good one and one that I asked myself.  As far as I can tell, pairwise probably does not produce as symmetrical a result as cr, resulting in an instability when using an unstable algorithm.

If you'd like to dig deeper, that would be most welcome.  My sense, however, is that this is a stability issue and thus consider that we can close the issue as as soon as the new navier4.f is put into the repo.
