### ISSUE TITLE
singlerod OpenACC errors on summitdev

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#381]
Last week, when using the "openacc" branch, I discovered that the "singlerod" example fails at runtime on summitdev.  The OpenACC runtime produces a "data partially present on device" error.  

I used a git bisect and and found that 03725f1bbf298de93ea812d6209778b2c4b1984d was the first bad commit on summitdev:
```
03725f1bbf298de93ea812d6209778b2c4b1984d is the first bad commit
commit 03725f1bbf298de93ea812d6209778b2c4b1984d
Author: Misun Min <mmin@mcs.anl.gov>
Date:   Mon Sep 25 08:21:25 2017 +0000

    [openacc] gpu timings improvement 1gpu/16cpu= 1.5
    
    - plan4_acc, acc, hmh_gmres significant reduction in redundancy
    - datacopy routine renamed, indicating istep info when called
    - current: singlerod 5 steps -> 1gpu: 15sec, 16cpu: 10sec (jlse)

:040000 040000 e7adcdb36df90518daa16caa301c5147417565fd 29a6a03369448bdbdbcccd65812e3ae99931c8cb M	core
```

This returned the runtime error:
```
FATAL ERROR: data in PRESENT clause was not found on device 1: name=a host:0x273e70300
```

**Comment by stgeke** [comment]
Can you please update me on this.

**Comment by RonRahaman** [comment]
I haven't addressed this issue yet.  My recent GPU efforts were the memory optimizations in PR #423

**Comment by misunmin** [comment]
This has been fixed. 
[590410990638aecfbf42e9a53cf8eb88af7c5b04]
