### ISSUE TITLE
Benard short test broken?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#392]
It seems like ray_dd does not run straight away?

It seems that reducing dt is required...

**Comment by fischer1** [comment]
It seems like ray_dd runs ok for pnpn-2, but not pnpn under the current settings.

The svn version seems to work for both pnpn and for pnpn-2

**Comment by fischer1** [comment]
Looks like we can reduce dt by half and this case will run.  I guess we should do that
so that this example works.

(It's quite impressive, we can get to 1707.764 when lx1=16.  I'm certain this is correct.

**Comment by stgeke** [comment]
Agreed!

btw: What's the reason to have this as a short-test rather than an example? Does it test a specific unit or feature what is otherwise not tested?

**Comment by stgeke** [comment]
The current benard short_test works now for Pn/Pn as well.
