### ISSUE TITLE
hpts() cant read history points

### ISSUE THREAD

**Issue by GerritBotha** [Nek5000/Nek5000#396]
Hi Neks

I have recently started using Nek and downloaded the github version.

I need to track the instantiations velocities  over a line in my domain. Following the update I created a file, hpts.in, with the xyz coordinates I wish to track and then calling hpts() in usrchk.

After Nek loads the restart file, it exits stating it cant read the history file.  Lane gave a work around:

you make the hpts.in file like normal
just name it his.dat or something
then in usrdat3 include the line
write(hisfle,'(a)') "his.dat"

This works, but it appends the data to the history points. Unlike the the svn version that creatses a new file.

Am I doing something wrong?

Regards

**Comment by stgeke** [comment]
Please provide “casename.his” containing your history points. The interpolated fields will be appended to this file. So it is used for input and output.

On 19 Oct 2017, at 15:50, GerritBotha <notifications@github.com <mailto:notifications@github.com> > wrote:

Hi Neks

I have recently started using Nek and downloaded the github version.

I need to track the instantiations velocities over a line in my domain. Following the update I created a file, hpts.in, with the xyz coordinates I wish to track and then calling hpts() in usrchk.

After Nek loads the restart file, it exits stating it cant read the history file. Lane gave a work around:

you make the hpts.in file like normal
just name it his.dat or something
then in usrdat3 include the line
write(hisfle,'(a)') "his.dat"

This works, but it appends the data to the history points. Unlike the the svn version that creatses a new file.

Am I doing something wrong?

Regards

**Comment by GerritBotha** [comment]
Hi Stefan

Please see attached file

[2s_2.0d.zip](https://github.com/Nek5000/Nek5000/files/1398892/2s_2.0d.zip)

Regards

**Comment by stgeke** [comment]
What should I do with this file? Please let me know if my reply does not resolve your problem.

**Comment by stgeke** [comment]
I was not asking for you .his file instead I wanted to tell you that you have to provide a casename.his instead of hpts.in. See release notes!

On 19 Oct 2017, at 17:16, Stefan K. <notifications@github.com <mailto:notifications@github.com> > wrote:

What should I do with this file? Please let me know if my reply does not resolve your problem.

**Comment by GerritBotha** [comment]
Hi Stefan

I re-downloaded Nek to ensure i have the newest version. Renamed my history
file to <casename>.his and called hpts() in the usrchck.

When running the code it renames my .his file to .his1 and exits with:

 done :: set initial conditions

 call userchk
 dump history points
 reading history points
 Cannot open history file in subroutine hpts()

call exitt: dying ...



On Thu, Oct 19, 2017 at 10:28 AM, Stefan K. <notifications@github.com>
wrote:

> I was not asking for you .his file instead I wanted to tell you that you
> have to provide a casename.his instead of hpts.in. See release notes!
>
> On 19 Oct 2017, at 17:16, Stefan K. <notifications@github.com <mailto:
> notifications@github.com> > wrote:
>
> What should I do with this file? Please let me know if my reply does not
> resolve your problem.
>
> —
> You are receiving this because you are subscribed to this thread.
>
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Nek5000_Nek5000_issues_396-23issuecomment-2D337944430&d=DwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=RXL-tgDJ2sb3-qTmHGTl4_0vfiloZLw2BjifFUmYPBg&m=heCSdIWRP92u1Gg6PkRffptG1USXp-qAbCmt9cJi1zU&s=8dPzwf0grun5bWFvUEFjc4_VypGXIUugEFfCBv_-ufw&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AfZRJEBd9Go59T-5FYoXuQIkENTzhsV3Ttks5st2qDgaJpZM4P-5FQhq&d=DwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=RXL-tgDJ2sb3-qTmHGTl4_0vfiloZLw2BjifFUmYPBg&m=heCSdIWRP92u1Gg6PkRffptG1USXp-qAbCmt9cJi1zU&s=YHPkC3CvGxpSCecVaBI3AvLgLlTJSTe7VJoph5576WM&e=>
> .
>



-- 

*Gerrit Botha* | *Graduate Research Assistant*


*M.Eng (Nuclear), B.Eng (Mechanical)*

Texas A&M Nuclear Engineering

M-103A AI Nuclear Engineering | 3133 TAMU | College Station, TX 77843-3133

(979) 422-6399

gerritbotha@tamu.edu <fatihsinan@tamu.edu>

**Comment by stgeke** [comment]
How do you launch your run? Are you using a script?

On 19 Oct 2017, at 23:10, GerritBotha <notifications@github.com <mailto:notifications@github.com> > wrote:

Hi Stefan

I re-downloaded Nek to ensure i have the newest version. Renamed my history
file to <casename>.his and called hpts() in the usrchck.

When running the code it renames my .his file to .his1 and exits with:

 done :: set initial conditions

 call userchk
 dump history points
 reading history points
 Cannot open history file in subroutine hpts()

call exitt: dying ...



On Thu, Oct 19, 2017 at 10:28 AM, Stefan K. <notifications@github.com <mailto:notifications@github.com> >
wrote:

> I was not asking for you .his file instead I wanted to tell you that you
> have to provide a casename.his instead of hpts.in. See release notes!
>
> On 19 Oct 2017, at 17:16, Stefan K. <notifications@github.com <mailto:notifications@github.com> <mailto:
> notifications@github.com <mailto:notifications@github.com> > > wrote:
>
> What should I do with this file? Please let me know if my reply does not
> resolve your problem.
>
> —
> You are receiving this because you are subscribed to this thread.
>
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Nek5000_Nek5000_issues_396-23issuecomment-2D337944430&d=DwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=RXL-tgDJ2sb3-qTmHGTl4_0vfiloZLw2BjifFUmYPBg&m=heCSdIWRP92u1Gg6PkRffptG1USXp-qAbCmt9cJi1zU&s=8dPzwf0grun5bWFvUEFjc4_VypGXIUugEFfCBv_-ufw&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AfZRJEBd9Go59T-5FYoXuQIkENTzhsV3Ttks5st2qDgaJpZM4P-5FQhq&d=DwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=RXL-tgDJ2sb3-qTmHGTl4_0vfiloZLw2BjifFUmYPBg&m=heCSdIWRP92u1Gg6PkRffptG1USXp-qAbCmt9cJi1zU&s=YHPkC3CvGxpSCecVaBI3AvLgLlTJSTe7VJoph5576WM&e=>
> .
>



-- 

*Gerrit Botha* | *Graduate Research Assistant*


*M.Eng (Nuclear), B.Eng (Mechanical)*

Texas A&M Nuclear Engineering

M-103A AI Nuclear Engineering | 3133 TAMU | College Station, TX 77843-3133

(979) 422-6399

gerritbotha@tamu.edu <mailto:gerritbotha@tamu.edu> <fatihsinan@tamu.edu <mailto:fatihsinan@tamu.edu> >

**Comment by GerritBotha** [comment]
Hi Stefan

No I just submit the job to Cetus using the submission script

Regards
G

On Thu, Oct 19, 2017 at 4:19 PM, Stefan K. <notifications@github.com> wrote:

> How do you launch your run? Are you using a script?
>
> On 19 Oct 2017, at 23:10, GerritBotha <notifications@github.com <mailto:
> notifications@github.com> > wrote:
>
> Hi Stefan
>
> I re-downloaded Nek to ensure i have the newest version. Renamed my history
> file to <casename>.his and called hpts() in the usrchck.
>
> When running the code it renames my .his file to .his1 and exits with:
>
> done :: set initial conditions
>
> call userchk
> dump history points
> reading history points
> Cannot open history file in subroutine hpts()
>
> call exitt: dying ...
>
>
>
> On Thu, Oct 19, 2017 at 10:28 AM, Stefan K. <notifications@github.com
> <mailto:notifications@github.com> >
> wrote:
>
> > I was not asking for you .his file instead I wanted to tell you that you
> > have to provide a casename.his instead of hpts.in. See release notes!
> >
> > On 19 Oct 2017, at 17:16, Stefan K. <notifications@github.com <mailto:
> notifications@github.com> <mailto:
> > notifications@github.com <mailto:notifications@github.com> > > wrote:
> >
> > What should I do with this file? Please let me know if my reply does not
> > resolve your problem.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> >
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://urldefense.proofpoint.com/v2/url?u=https-
> 3A__github.com_Nek5000_Nek5000_issues_396-23issuecomment-2D337944430&d=
> DwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=RXL-tgDJ2sb3-qTmHGTl4_
> 0vfiloZLw2BjifFUmYPBg&m=heCSdIWRP92u1Gg6PkRffptG1USXp-qAbCmt9cJi1zU&s=
> 8dPzwf0grun5bWFvUEFjc4_VypGXIUugEFfCBv_-ufw&e=>,
> > or mute the thread
> > <https://urldefense.proofpoint.com/v2/url?u=https-
> 3A__github.com_notifications_unsubscribe-2Dauth_AfZRJEBd9Go59T-
> 5FYoXuQIkENTzhsV3Ttks5st2qDgaJpZM4P-5FQhq&d=DwMFaQ&c=ODFT-
> G5SujMiGrKuoJJjVg&r=RXL-tgDJ2sb3-qTmHGTl4_0vfiloZLw2BjifFUmYPBg&m=
> heCSdIWRP92u1Gg6PkRffptG1USXp-qAbCmt9cJi1zU&s=
> YHPkC3CvGxpSCecVaBI3AvLgLlTJSTe7VJoph5576WM&e=>
> > .
> >
>
>
>
> --
>
> *Gerrit Botha* | *Graduate Research Assistant*
>
>
> *M.Eng (Nuclear), B.Eng (Mechanical)*
>
> Texas A&M Nuclear Engineering
>
> M-103A AI Nuclear Engineering | 3133 TAMU | College Station, TX 77843-3133
>
> (979) 422-6399
>
> gerritbotha@tamu.edu <mailto:gerritbotha@tamu.edu> <fatihsinan@tamu.edu
> <mailto:fatihsinan@tamu.edu> >
>
> —
> You are receiving this because you modified the open/close state.
>
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Nek5000_Nek5000_issues_396-23issuecomment-2D338041308&d=DwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=RXL-tgDJ2sb3-qTmHGTl4_0vfiloZLw2BjifFUmYPBg&m=zoyswADx6bQ90UMP2nngSZA7mLeFEs4sOl4n2S2Co84&s=9rAXBlu9I5ZlcJK8resRGb0T8WgsBrHRYx6x9CCsHtU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AfZRJMs5ijGQ1uZUBXOIjq0IrU0nI3D1ks5st7z7gaJpZM4P-5FQhq&d=DwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=RXL-tgDJ2sb3-qTmHGTl4_0vfiloZLw2BjifFUmYPBg&m=zoyswADx6bQ90UMP2nngSZA7mLeFEs4sOl4n2S2Co84&s=kwHwP0NagwkQ4YyKBXThZt4ZQ5F0ud-Jif0B3tmaKSw&e=>
> .
>



-- 

*Gerrit Botha* | *Graduate Research Assistant*


*M.Eng (Nuclear), B.Eng (Mechanical)*

Texas A&M Nuclear Engineering

M-103A AI Nuclear Engineering | 3133 TAMU | College Station, TX 77843-3133

(979) 422-6399

gerritbotha@tamu.edu <fatihsinan@tamu.edu>

**Comment by stgeke** [comment]
I cannot reproduce what you see. It looks like something is renaming your .his file. May be your job submission script?
