### ISSUE TITLE
findpts_setup

### ISSUE THREAD

**Issue by GerritBotha** [Nek5000/Nek5000#401]
Hey Neks
 Hope someone can help me with this. I have a script that calculates the y+ values of my domain and dumps it in one of the passive scalars. 

When it comes to compiling I get a invalid reference to findpts_setup, findpts and findpts_eval while using the newest github version of NEK. Going thought the code I find, under the 3rd party codes, that I do have a findpts.c file where the routines are located, but still NEK does not reference them?

Regards

**Comment by stgeke** [comment]
All gslib routines have been prefixed with "fgslib" (just run grep in core). So you have to call fgslib_findpts(...)

-----Original message-----

**Comment by GerritBotha** [comment]
Thank you!

**Comment by dovizio** [comment]
Hi Gerrit,

Did you manage to get the script right?
I am looking for the same script and would be glad if you can share it.

Thanks

**Comment by stgeke** [comment]
Please use the mailing list for requests like this.
