### ISSUE TITLE
wget for gslib instalation on cray

### ISSUE THREAD

**Issue by adampep** [Nek5000/Nek5000#419]
Hi. We've just discovered that wget does not work the same way on our local cray computer as on our laptops, so we cannot compile current nek version there. It does download gslib code, but cuts tar.gz extension and cause compilation to stop

**Comment by stgeke** [comment]
Ok I will check. 
btw: The release will come with all required tarballs.

-----Original message-----

**Comment by stgeke** [comment]
Does it work if you replace

  wget https://github.com/gslib/gslib/archive/v$VER.tar.gz

by

 wget -O v$VER.tar.gz https://github.com/gslib/gslib/archive/v$VER.tar.gz

in gslib/install

-----Original message-----

**Comment by stgeke** [comment]
Adam, can you please confirm if the latest fix works for you.

**Comment by stgeke** [comment]
Fixed
