### ISSUE TITLE
prenek is broken when made with `./maketools all`

### ISSUE THREAD

**Issue by kent0** [Nek5000/Nek5000#424]
When I make prenek with `./maketools all` and run `prex`, the screen does not show the usual red banner on the right; and when I type in a response, it does not move onto the next query.

When I make prenek with `./maketools prenek` (after `./maketools clean`) and run `prex`, everything works as expected.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/15679de982c7cb41e72ec278ef6b5c39c1ade931
