### ISSUE TITLE
Incorrect results with Cray compiler

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#430]
I tested Pn/Pn and Pn/Pn2.
The results are correct if the was compiled without optimizations `-O0`.

**Comment by njansson** [comment]
We were about to push a fix for this. One of the arrays in semhat (fast3d) is declared as `w(0:1)` while being `w(0:2*n+1)`, causing various badness.

**Comment by stgeke** [comment]
I tested the Ethier short test with PR #432 and the results are still incorrect. The pressure and velocity solve converges but the initial residual is wrong. For now I am disabling the support for the Cray compilers.

**Comment by fischer1** [comment]
Does this mean we can't run on the Cray ?

(I guess Cray supports other compilers?)

I can ask one of the students to look into this....  There must be a Cray flag that admits
the 

      a(0:1) , b(1)

type declarations as they are part of linpack / LAPACK and therefore must be
part of the fortran standard.   (For example, in linpack, when you pass in an array
A, you pass only  lda, not lda and tda:

      subroutine dgefa(a,lda,m,n)

       real a(lda,1)

        do j=1,n
         do i=1,m
              a(i,j) = blah
        enddo
        enddo

which allows you to access any submatrix of the originally declared block of
memory that [a] points to.

Probably there is a flag, or a reduction in optimization level, that would allow this
to be compiled.   I guess I could check the Univ. Tennessee team...

**Comment by stgeke** [comment]
No Cray machines support other compilers like Intel. I don't think there is such a flag. It has to do with some compiler optimizations because it works with "-O0". We can look into the assembler code to figure out what's going on in this case. However, it looks like there are other things which go wrong. 

-----Original message-----

**Comment by fischer1** [comment]
This might be why we have the LAPACK routines compiled with -O0, which always freaks people out...
(of course, they are not in our core kernels)

**Comment by pschlatt1** [comment]
Indeed, the declared size of the dummy array "w" should not matter in Fortran 77, as long as the array that is passed in is large enough (the old Fortran style would have been to declare it w(*) if I remember well. If it started at 1 that is). However, -O0 might also change the internal memory layout, so there might still be a memory issue somewhere that goes undetected.

**Comment by stgeke** [comment]
Cray compiler seems to work with #557 now. May be this because of a new Cray compiler version.
