### ISSUE TITLE
Example demonstrating the new g2gi feature?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#437]
The question has arisen on how to use the new g2gi restart feature.

Could we have an example that demo's how to do this?

**Comment by stgeke** [comment]
I guess you are talking about the generic fld reader (gflr). The usage is pretty simple (e.g. in usrchk):

```
call gfldr('my restart file')
```

**Comment by stgeke** [comment]
I agree with you - an example is useful. I am closing this issue as this request needs to go to the NekExamples repo.
