### ISSUE TITLE
Compilation error for exo2nek on Ubuntu16.04

### ISSUE THREAD

**Issue by rajeeja** [Nek5000/Nek5000#439]
make[1]: Leaving directory '/home/jain/exo2nek_Nek5000/tools/exo2nek/3rd_party/seacas-exodus/build'
f77 -c  -I./3rd_party/seacas-exodus/packages/seacas/libraries/exodus_for/include exo2nek.f
Warning: exo2nek.f:3: Illegal preprocessor directive
Warning: exo2nek.f:14: Illegal preprocessor directive
Warning: exo2nek.f:43: Illegal preprocessor directive
Warning: exo2nek.f:231: Illegal preprocessor directive
Warning: exo2nek.f:311: Illegal preprocessor directive
Warning: exo2nek.f:327: Illegal preprocessor directive
Warning: exo2nek.f:349: Illegal preprocessor directive
Warning: exo2nek.f:411: Illegal preprocessor directive
Warning: exo2nek.f:454: Illegal preprocessor directive
Warning: exo2nek.f:506: Illegal preprocessor directive
Warning: exo2nek.f:564: Illegal preprocessor directive
exo2nek.f:257:12:

             xm1(jvert,1,1,iel)=x_exo(connect(nvert*(iel-1)+ivert))
            1
Error: Unclassifiable statement at (1)
exo2nek.f:258:12:

             ym1(jvert,1,1,iel)=y_exo(connect(nvert*(iel-1)+ivert))
            1
Error: Unclassifiable statement at (1)
exo2nek.f:261:12:

             xm1(jvert,1,1,iel)=x_exo(connect(nvert*(iel-1)+ivert))
            1
Error: Unclassifiable statement at (1)
exo2nek.f:262:12:

             ym1(jvert,1,1,iel)=y_exo(connect(nvert*(iel-1)+ivert))
            1
Error: Unclassifiable statement at (1)
exo2nek.f:263:12:

             zm1(jvert,1,1,iel)=z_exo(connect(nvert*(iel-1)+ivert))
            1
Error: Unclassifiable statement at (1)
exo2nek.f:295:72: Error: Unexpected STATEMENT FUNCTION statement at (1)
exo2nek.f:296:16:

                 bc (5,jfc,iel) = idss(iss)
                1
Error: Unclassifiable statement at (1)
exo2nek.f:552:31:

             if (h.gt.tol2*len) ccurve(i,e) = 'm'
                               1
Error: Cannot assign to a named constant at (1)
exo2nek.f:22:18:

       call blank (exoname, 32)
                  1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(4) to CHARACTER(1)
exo2nek.f:23:18:

       call blank (re2name, 80)
                  1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(4) to CHARACTER(1)
exo2nek.f:27:19:

       len = ltrunc(exoname,32)
                   1
Warning: Type mismatch in argument ‘string’ at (1); passed REAL(4) to CHARACTER(1)
exo2nek.f:29:18:

       call chcopy(re2name        ,exoname,32)
                  1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(4) to CHARACTER(1)
exo2nek.f:51:34:

       integer idblk              (max_num_elem_blk)
                                  1
Error: Variable ‘max_num_elem_blk’ cannot appear in the expression at (1)
exo2nek.f:52:34:

       integer num_attr           (max_num_elem_blk)  ! not used
                                  1
Error: Variable ‘max_num_elem_blk’ cannot appear in the expression at (1)
exo2nek.f:53:34:

       integer num_nodes_per_elem (max_num_elem_blk)
                                  1
Error: Variable ‘max_num_elem_blk’ cannot appear in the expression at (1)
exo2nek.f:270:20:

       call blank   (cbc,3*2*ldim*max_num_elem)
                    1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(4) to CHARACTER(1)
exo2nek.f:271:20:

       call rzero   (bc,5*2*ldim*max_num_elem)
                    1
Warning: Rank mismatch in argument ‘a’ at (1) (rank-1 and scalar)
exo2nek.f:272:20:

       call blank   (ccurve,(4+8*(ldim-2))*max_num_elem)
                    1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(4) to CHARACTER(1)
exo2nek.f:273:20:

       call rzero   (curve,2*ldim*12*max_num_elem)
                    1
Warning: Rank mismatch in argument ‘a’ at (1) (rank-1 and scalar)
exo2nek.f:392:28:

           call copy        (buf2(1) ,xx,8)
                            1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to REAL(4)
exo2nek.f:393:28:

           call copy        (buf2(9) ,yy,8)
                            1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to REAL(4)
exo2nek.f:394:28:

           call copy        (buf2(17),zz,8)
                            1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to REAL(4)
exo2nek.f:399:28:

           call copy        (buf2(1),xx,4)
                            1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to REAL(4)
exo2nek.f:400:28:

           call copy        (buf2(5),yy,4)
                            1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to REAL(4)
exo2nek.f:519:24:

       call chcopy(ccrve,ccurve(1,e),12)
                        1
Warning: Type mismatch in argument ‘b’ at (1); passed REAL(4) to CHARACTER(1)
exo2nek.f:597:26:

           call gen_int_gz(j,jt,w,n,z,m)
                          1
Warning: Type mismatch in argument ‘j’ at (1); passed INTEGER(4) to REAL(4)
exo2nek.f:623:26:

           call gen_int_gz(j,jt,w,n,z,m)
                          1
Warning: Type mismatch in argument ‘j’ at (1); passed INTEGER(4) to REAL(4)
exo2nek.f:521:29:

       call map2reg     (x3,3,xm1(1,1,1,e),1)  ! Map to 3x3x3 array
                             1
Warning: Rank mismatch in argument ‘u’ at (1) (rank-2 and scalar)
exo2nek.f:522:29:

       call map2reg     (y3,3,ym1(1,1,1,e),1)
                             1
Warning: Rank mismatch in argument ‘u’ at (1) (rank-2 and scalar)
exo2nek.f:523:46:

       if (num_dim.eq.3) call map2reg    (z3,3,zm1(1,1,1,e),1)
                                              1
Warning: Rank mismatch in argument ‘u’ at (1) (rank-2 and scalar)
exo2nek.f:526:10:

       if (ccurve(5,e).eq.'s') then
          1
Error: Operands of comparison operator '.eq.' at (1) are REAL(4)/CHARACTER(1)
exo2nek.f:530:10:

       if (ccurve(6,e).eq.'s') then
          1
Error: Operands of comparison operator '.eq.' at (1) are REAL(4)/CHARACTER(1)
exo2nek.f:553:42:

             if (h.gt.tol2*len) call copy (curve(1,i,e),xyz(1,2),num_dim)
                                          1
Warning: Rank mismatch in argument ‘a’ at (1) (rank-1 and scalar)
exo2nek.f:426:14:

           if (ccurve(iedge,iel).ne.' ') ncurv = ncurv+1
              1
Error: Operands of comparison operator '.ne.' at (1) are REAL(4)/CHARACTER(1)
exo2nek.f:435:14:

           if (ccurve(iedge,iel).ne.' ') then
              1
Error: Operands of comparison operator '.ne.' at (1) are REAL(4)/CHARACTER(1)
exo2nek.f:436:16:

             if (ccurve(iedge,iel).eq.'C') cc='C'
                1
Error: Operands of comparison operator '.eq.' at (1) are REAL(4)/CHARACTER(1)
exo2nek.f:437:16:

             if (ccurve(iedge,iel).eq.'s') cc='s'
                1
Error: Operands of comparison operator '.eq.' at (1) are REAL(4)/CHARACTER(1)
exo2nek.f:438:16:

             if (ccurve(iedge,iel).eq.'m') cc='m'
                1
Error: Operands of comparison operator '.eq.' at (1) are REAL(4)/CHARACTER(1)
exo2nek.f:441:29:

             call copy       (buf2(3),curve(1,iedge,iel),5)
                             1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to REAL(4)
exo2nek.f:442:29:

             call blank      (buf2(8),8)
                             1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to CHARACTER(1)
exo2nek.f:443:29:

             call chcopy     (buf2(8),cc,1)
                             1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to CHARACTER(1)
exo2nek.f:469:14:

           if (cbc(ifc,iel).ne.'   ')  nbc = nbc + 1
              1
Error: Operands of comparison operator '.ne.' at (1) are REAL(4)/CHARACTER(1)
exo2nek.f:478:16:

           ch3 = cbc(ifc,iel)
                1
Error: Can't convert REAL(4) to CHARACTER(1) at (1)
exo2nek.f:482:25:

             call copy   (buf2(3),bc(1,ifc,iel),5)
                         1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to REAL(4)
exo2nek.f:483:25:

             call blank  (buf2(8),8)
                         1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to CHARACTER(1)
exo2nek.f:484:25:

             call chcopy (buf2(8),ch3,3)
                         1
Warning: Type mismatch in argument ‘a’ at (1); passed REAL(8) to CHARACTER(1)
makefile:21: recipe for target 'exo2nek.o' failed
make: *** [exo2nek.o] Error 1

**Comment by stgeke** [comment]
What Fortran compiler are you using?

-----Original message-----

**Comment by rajeeja** [comment]
I have gfortran, but the problem is different.
Found it. I was doing "make" in exo2nek folder.
I should have done: ./maketools exo2nek in the tools directory.

**Comment by stgeke** [comment]
This will not work. All the tools have to be compiled using our maketools script.
