### ISSUE TITLE
Redirect stdout

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#444]
I think we should replace all

```
write(6,
write(*,
```

by `write(ustdout,`

This will allow us to write into different logfiles in case of multi-session runs.

**Comment by fischer1** [comment]
That would push a lot of lines over the 72 character limit --- but I agree with the principle.

I just learned (can you confirm?) that it's possible to change stdout in C and we could
handle the issue that way ?

**Comment by stgeke** [comment]
Yes in C it's easy. In Fortran 77 that's the only way I can think of.

-----Original message-----

**Comment by fischer1** [comment]
My understanding is the following ---

Once std.out is redefined (by a piece of C code), then write(6,*) will write to std.out -- which
is the definition given by the C code, so it all should be good?


________________________________

**Comment by stgeke** [comment]
In C you can only redirect the output of say printf() not the stdout of the process, so the Fortran runtime library (implementing write) would not know about the redirection. 


-----Original message-----

**Comment by fischer1** [comment]
OK... thanks.  One of my group was indicating otherwise...

We could just use the single character "o" for std. out --- it is not used anywhere.

      if (nio.eq.0) write(o,1) stuff


________________________________

**Comment by stgeke** [comment]
Yes but this is also error prone if a user has a local 'o' variable. Something more unique would be good. 

-----Original message-----

**Comment by stgeke** [comment]
Implemented in https://github.com/Nek5000/Nek5000/pull/456
In fact I was wrong. The C library function freopen redirects even the Fortran output.
