### ISSUE TITLE
eddy_rich short_test fails

### ISSUE THREAD

**Issue by hackljf** [Nek5000/Nek5000#445]
travis has complained about eddy_rich after testing my attempt to pull 6286a2ccacee79e15dcefd02c5dd93d0747fff98
into UFCCMT. 

    SUCCESS: gmres: Test value 15.0 equals target value 0.0 +/- 20.0
    FAILURE: X err: Test value 0.0001442382 exceeds target value 5.497982e-05 +/- 1e-06
    FAILURE: Y err: Test value 0.0001376785 exceeds target value 8.064398e-05 +/- 1e-06
    FAILURE: P err: Test value 0.0006785378 exceeds target value 0.0002272926 +/- 0.0001

It also complains about this by the sixth step.
 ERROR:  alphad .le. 0 in econjp  -5.7718087455521319E-007           6

I'm going to pull anyway. When I ran eddy_rich on an older version of nek5000, it suffered the same negative-alphad ERRORs. So I still trust the code.

**Comment by stgeke** [comment]
This bug was introduced with the latest projection changes. Look like only Richardson is affected. In all other use cases projection works fine.

**Comment by hackljf** [comment]
Thank you for clarifying. Just to make sure I understand, I ask: are the errors I show acceptable when I merge from upstream? May I assume they are not show-stoppers that recommend against merging to keep CMT-nek current with nek5000?

**Comment by stgeke** [comment]
I disabled the velocity residual projection for this short_test to make it pass. I do not close this issue because we have to revisit this problem.

**Comment by hackljf** [comment]
Thank you Stefan. While I think there was a broad understanding and
accommodation of this issue, it's always nice to see Travis report success!

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/pull/459
