### ISSUE TITLE
Recompile automatically if a makenek variable changed

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#446]
Currently this is error prone e.g. when the user changes PPLIST a full recompilation is required.

**Comment by RonRahaman** [comment]
Perhaps `makenek.inc` could include logic to check if the user's `makenek` file is newer than the respective `nek5000` binary?

**Comment by stgeke** [comment]
My plan was dump all relevant variables into a file e.g. `.state`. If the variables change (diff of current variables and .state is zero) I trigger a rebuild.

**Comment by RonRahaman** [comment]
That sounds much more robust.  I know that autotools will sometimes complain about clock skew when it's attempting the same check, so your method would avoid that problem.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/8499b9a5d6bc0402df7419fa22eabef894395457
