### ISSUE TITLE
Non-zero return values upon error?

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#448]
I see that in many cases, Nek5000 will return zero even if an error occurs.  For example, `err_chk` will print an error message to stdout, but it will still call `exitt`, which returns 0.  Would you consider adding non-zero codes for the different classes of errors?

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/8499b9a5d6bc0402df7419fa22eabef894395457
