### ISSUE TITLE
Explain our github workflow on the wiki

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#46]
Just created the following wiki article 
https://github.com/Nek5000/Nek5000/wiki/GitHub-workflow-and-branching-conventions

My main motivation was to summarize the basic concepts so that a newbie (like me) knows what to do. I am happy to discuss the suggested workflow and conventions.

**Comment by maxhutch** [comment]
Yes, this is great!  I took a look at what you've written.  

Do we want to impose a 1-to-1 mapping between issues and branches.  I had thought we'd start with a more flexible "feature branch" model, where feature deliberately doesn't quite line up with github vocab.  Those feature branches could be directed at one or more issues, but could also just be issue-less quick tweaks to exploring new ideas.

Maybe the NE guys would prefer a bit more structure?

CC: @emerzari @RonRahaman

**Comment by stgeke** [comment]
I like the 1-to-1 mapping because it forces you to commit as small and atomic as possible. You also get a good understanding what the change is about. Sometimes this gets lost in translation using a 'commit message'. Sure, on that other hand it's not very flexible and for quick tweaks it's too heavy.

**Comment by maxhutch** [comment]
Yeah, I think its good to exclude one (branch) to many (issues).  I'm more
concerned with one (branch) to zero (issues): expecting the creation of an
issue to go along with the creation of a branch, especially because the
pull request itself has the ability to record a conversation about that
merge.

**Comment by stgeke** [comment]
I am with you on that. How do you know who is working on what? Even with a descriptive branch name it's hard to get. Any ideas?

**Comment by maxhutch** [comment]
Right now, you don't.   Nek5000 development is decoupled enough that the
likelihood of duplicating effort is naturally low.  Maybe KTH is more
tightly coupled, in which case they might want to form their own
convention, but what they want to do internally might not suit Argonne or
UIUC.

In other words, if you want everyone else to be aware of what you are
working on, then you should create a corresponding issue, assign it to
yourself, and reference it in the branch name.  But if you're not concerned
about other people being unaware then maybe you skip those steps.

**Comment by stgeke** [comment]
Sounds good to me.

**Comment by maxhutch** [comment]
Let's give people a chance to chime in.  Plan on closing this on Wednesday (post-group meeting)?  @RonRahaman , I'm still out of town if you want to bring it up.

**Comment by RonRahaman** [comment]
Yes, I will.  

@stgeke, I really like your clear use of issue branches, and I think we should  to present that as the endorsed method (just as you did in your wiki post).  

As @maxhutch  suggested, I"m also happy to allow people to relax their use of issue branches at their discretion..
