### ISSUE TITLE
postprocessing with Paraview

### ISSUE THREAD

**Issue by XXXXThomas** [Nek5000/Nek5000#461]
Hi, dear experts on Nek5000
    I am a freshman here and I want to visualize the result by Paraview. Could you please give some suggestions how I could reach the goal. Thank you very much.

**Comment by lcarasik** [comment]
Hi Thomas,

This isn't the best place for a question such as this. Have you followed the tutorial here? http://nek5000.github.io/NekDoc/tutorials.html

Edit: Don't say sorry! It's alright to ask questions, but it might be better to focus them towards the nek user mailing list: https://nek5000.mcs.anl.gov/community/

**Comment by XXXXThomas** [comment]
Hi lcarasik
    Thank you for your helpful link and I am also very sorry to ask questions here. I will try my best to learn from the tutorials.
    Edit：Thank you for your sincere comment for me about shooting my troubles and I have tried to send email to nek5000-users@lists.mcs.anl.gov for any useful suggestions. But I have not received any reply yet. And what I am querying about is the format issue: what format I should select for .nek5000 file in PARAVIEW that the file could be identified by the post-processing software. Thank you and hope for your reply.              
                                                                                                  XTOM
