### ISSUE TITLE
makenek: use fixed-format flags for XL compilers?

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#463]
Could we update makenek so that, for the IBM XL compilers, a fixed-format flag (like `-qfixed=72`) is automatically used?

On Summitdev, when you load the XL modules, mpif77 is aliased to xlf90: 

``` Console
rahaman@summitdev-login1:~$ which mpif77
/autofs/nccs-svm1_sw/summitdev/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20170914-beta/spectrum-mpi-10.1.0.4-20170915-nmlgpsufnxxal2wv64hh7zfisabr56ry/bin/mpif77
rahaman@summitdev-login1:~$ mpif77 -show
/sw/summitdev/xl/20170914-beta/xlf/15.1.6/bin/xlf90 -I/autofs/nccs-svm1_sw/summitdev/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20170914-beta/spectrum-mpi-10.1.0.4-20170915-nmlgpsufnxxal2wv64hh7zfisabr56ry/include -qthreaded -I/autofs/nccs-svm1_sw/summitdev/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20170914-beta/spectrum-mpi-10.1.0.4-20170915-nmlgpsufnxxal2wv64hh7zfisabr56ry/lib/XL -L/tmp/lepera/yeti_10010004_RTM/ibm-smpi/ompibase/dependencies/lib -L/autofs/nccs-svm1_sw/summitdev/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20170914-beta/spectrum-mpi-10.1.0.4-20170915-nmlgpsufnxxal2wv64hh7zfisabr56ry/lib -lmpiprofilesupport -lmpi_usempi -lmpi_mpifh -lmpi_ibm
```
so we get syntax errors without the `-qfixed` flag.  

It's easy to workaround by adding `-qfixed` to makenek myself, and I'm not sure if the mpf77 --> xlf90 aliasing is an issue on many other systems.  But I think it would do some help and no harm if `-qfixed` was set automatically.

**Comment by stgeke** [comment]
Yes we can add this flag, if this helps.

**Comment by stgeke** [comment]
@RonRahaman Can you please test this on Cetus/Mira. I just want to ensure that we don't break our build system.

**Comment by RonRahaman** [comment]
Sure, I will check it out

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/pull/491
