### ISSUE TITLE
maketools for intel compiler

### ISSUE THREAD

**Issue by adampep** [Nek5000/Nek5000#464]
There is a problem with intel compiler on jenkis which appeared after mpi wrappers were used for compiling tools. After some checking I found, that on some machines (e.g. cray) mcmodel conflicts with mpi wrapper. So I can compile:
ifort -c -DMAXNEL=150000 -fpp -shared-intel -mcmodel=medium -r8 genmap.f
but mpi wrapper
ftn -c -DMAXNEL=150000 -fpp -shared-intel -mcmodel=medium -r8 genmap.f
gives
ifort: command line error: '-static' conflicts with '-mcmodel'

This error does not show up for -mcmodel=small. Other compilers do not show this problem. I'm not sure whether it is a problem of the way mpi was compiled or internal intel problem.

**Comment by stgeke** [comment]
It a matter how you configure the wrapper. In your case the wrapper invokes (for whatever reason) -static

On 17 Jan 2018, at 11:54, Adam Peplinski <notifications@github.com <mailto:notifications@github.com> > wrote:

There is a problem with intel compiler on jenkis which appeared after mpi wrappers were used for compiling tools. After some checking I found, that on some machines (e.g. cray) mcmodel conflicts with mpi wrapper. So I can compile:
ifort -c -DMAXNEL=150000 -fpp -shared-intel -mcmodel=medium -r8 genmap.f
but mpi wrapper
ftn -c -DMAXNEL=150000 -fpp -shared-intel -mcmodel=medium -r8 genmap.f
gives
ifort: command line error: '-static' conflicts with '-mcmodel'

This error does not show up for -mcmodel=small. Other compilers do not show this problem. I'm not sure whether it is a problem of the way mpi was compiled or internal intel problem.

**Comment by adampep** [comment]
It seems to be slightly more complex. I've contacted support and they said cray has  CRAYPE_LINK_TYPE variable defining way of linking, so on cray one should set it to dynamic. Other solution would be adding -dynamic flag to intel directly in maketools. It seems to work on our cray.

**Comment by stgeke** [comment]
I see. Here something else we have to think about: Most wrapper are designed for the compute nodes and not for the login node where you typically compile and run the tools.

On 18 Jan 2018, at 14:48, Adam Peplinski <notifications@github.com <mailto:notifications@github.com> > wrote:

It seems to be slightly more complex. I've contacted support and they said cray has CRAYPE_LINK_TYPE variable defining way of linking, so on cray one should set it to dynamic. Other solution would be adding -dynamic flag to intel directly in maketools. It seems to work on our cray.

**Comment by stgeke** [comment]
Can we close this issue or is there anything we need to fix/change?

**Comment by adampep** [comment]
No, I think we can leave it the way it is right now. I will test -dynamic flag on cray and possibly make pull request.
