### ISSUE TITLE
why is this posted on github?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#466]
ensure that you have at least 50 elements per MPI process (the more the better)

??

[ I sort of get it --- it depends on target audience --- but, it's totally wrong?!? ]

The fewer the better, of course --- but you have to think.

?

**Comment by stgeke** [comment]
Is this in the documentation? In this case, please open an issue in NekDoc.

You are right, this is wrong if you are interested in time to solution. I guess this is an old advise regarding parallel efficiency.

On 22 Jan 2018, at 00:10, fischer1 <notifications@github.com <mailto:notifications@github.com> > wrote:

ensure that you have at least 50 elements per MPI process (the more the better)

??

[ I sort of get it --- it depends on target audience --- but, it's totally wrong?!? ]

The fewer the better, of course --- but you have to think.

?
