### ISSUE TITLE
Cannot turn off projection for velocity

### ISSUE THREAD

**Issue by nicooff** [Nek5000/Nek5000#467]
Hi,

When using PnPn-2, it looks like projection is turned on based on the value of `param(94)` only and not via the variable `ifprojfld`.  In `plan3`:

`mstep = abs(param(94))`
`if (param(94).ne.0. .and. istep.ge.mstep) then`
`   call ophinv_pr(dv1,dv2,dv3,resv1,resv2,resv3,h1,h2,tolhv,nmxh)`

and in subroutine `ophinv_pr`:

`ifproj = .false.`
`if (param(94).gt.0)    ifproj = .true.`
`if (ifprojfld(ifield)) ifproj = .true.`

Since `param(94)` cannot be accessed by the user via the .par file and is set to 5 by default (and it is not set to 0 if projection is turned off), it seems that projection for the velocity cannot be turned off when using PnPn-2.

**Comment by stgeke** [comment]
It works for me. How can I reproduce what you see?

**Comment by nicooff** [comment]
One colleague had the problem when using cyclic boundary condition. I will ask for the files.

**Comment by stgeke** [comment]
It looks like we do not call the coupled helmholtz solver if ifcyclic=true and p94>0 (default with par). This will produce incorrect results!

Having this in mind it is currently not possible to call the correct (coupled) helmholtz solver using par or rea with projection.
