### ISSUE TITLE
Add conjugate heat transfer support for gfldr

### ISSUE THREAD

**Issue by kent0** [Nek5000/Nek5000#471]
I think g2gi had support for cht, and I would like to use that functionality with the new version.

**Comment by stgeke** [comment]
I don't recall why I disabled it. Looks like it should work out of the box. Let me do some tests ...

**Comment by kmittal2** [comment]
Did you ever get a chance to look into this? I just tried it on a cht case, and seems like it works.

**Comment by stgeke** [comment]
Yes this is fixed in the upcoming version.

On 7 Sep 2018, at 20:53, k10 <notifications@github.com <mailto:notifications@github.com> > wrote:

Did you ever get a chance to look into this? I just tried it on a cht case, and seems like it works.

**Comment by stgeke** [comment]
Implement in #520
