### ISSUE TITLE
Support for IFAXIS + IFSTRS 

### ISSUE THREAD

**Issue by ggiannako** [Nek5000/Nek5000#474]
It would be nice to support IFSTRS=T (required if we want to have variable viscosity) when IFAXIS=T is used.

**Comment by stgeke** [comment]
The code seems to work with this combination but the result is wrong.

**Comment by ggiannako** [comment]
I know @ananiast is working on it.

**Comment by stgeke** [comment]
@ggiannako @ananiast Can you please update me on this.
