### ISSUE TITLE
Implement Dong boundary condition

### ISSUE THREAD

**Issue by pschlatt1** [Nek5000/Nek5000#477]
Port the Dong boundary condition to the new version of Nek5000, including all the necessary changes in brdy.f, navier8.f, planx.f and a working user file.

**Comment by stgeke** [comment]
Good idea. Let’s support PnPn as well and provide an example in NekExamples.

On 14 Mar 2018, at 09:13, Philipp Schlatter <notifications@github.com <mailto:notifications@github.com> > wrote:

Port the Dong boundary condition to the new version of Nek5000, including all the necessary changes in brdy.f, navier8.f, planx.f and a working user file.

**Comment by stgeke** [comment]
For now included in an example https://github.com/Nek5000/NekExamples/commit/bce629cbc51f200e768fb787d0ebe077d8be3b51
