### ISSUE TITLE
ioinfo doesn't work when iostep=iotime=0

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#487]
ioinfo isn't working when iostep=0 and iotime=0, but it should.

**Comment by stgeke** [comment]
This is a feature - otherwise there is no way to disable all I/O (which can be useful to performance debugging).

**Comment by fischer1** [comment]
Maybe we need a "noio flag set in the usr file?"


This is not a good feature, because once a job is launched there is no way to

get an output with those settings.


The ioinfo feature was installed precisely so that someone could rescue a job that

is not going to complete in a timely fashion, without have to restart from from

the beginning.


?


________________________________
