### ISSUE TITLE
Par does not support flow-rate prescription

### ISSUE THREAD

**Issue by kent0** [Nek5000/Nek5000#488]
Currently there doesn't seem to be a par dictionary key for param(54) and param(55) which control fixed flow rate / Ubar.

**Comment by stgeke** [comment]
Yes, not all rea file parameters are and will be supported. Use the .usr file instead.

Note, there is a PR for p55/p55.

On 26 Apr 2018, at 00:30, Kento Kaneko <notifications@github.com <mailto:notifications@github.com> > wrote:

Currently there doesn't seem to be a par dictionary key for param(54) and param(55) which control fixed flow rate / Ubar.
