### ISSUE TITLE
Reader/Writer for Particle Data

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#490]
Name: particle%05d.vtu

Format: VTK XML unstructured grid, binary
Data:

* position
* vector or scalar quantities like (velocity or temperature)

Note: implementation shall use MPIIO but no other libraries like vtk

**Comment by dutta5** [comment]
Hi Stefan, 

when you say, "particle quantities defined in par" , 
 will the parameters that characterize the particles have to be defined in the *.par file ? 

What if we don't have multiple diameter, etc. for the particles ?

I think the ideal thing would be to allow the user to define the particles' initial condition. 
And have a subroutine to write the out the particle result files. 

As you mentioned, the result file should contain, 
> position
> velocity
> diameter/radii
> 
>
and the option to add more fields like temperature, particle id, etc. 

With Prof. Fischer, we already have a routine that does it, but the writing is now done by node 0,
so it is relatively slow for large number of particles.

**Comment by stgeke** [comment]
You will not define the parameters like the initial diameter of a particle. Instead you want to specify the particle quantities, how they map into volume fields and what get's dumped into a file.

**Comment by stgeke** [comment]
For now we will focus on the writer/reader and specify all required parameters in the usr file (instead of using par).

**Comment by dutta5** [comment]
hi Stefan, 

thank you for clarifying. 
As you mentioned, 
total number of particles and the number of related fields should be defined in the *.par file. 
When you say, "how they map into volume fields", are you talking about the findpts order stuff ?

**Comment by stgeke** [comment]
No this parameter is required for two-way Lagrangian particles.

**Comment by stgeke** [comment]
Implemented in https://github.com/Nek5000/Nek5000/commit/f3295153a8c780a28f601d1ea9bd10b15895a637
