### ISSUE TITLE
No info on how to git / build gslib

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#493]
We should list gslib on the Nek5000 git page -- and we should provide, somewhere, full instructions on how to build the current repo version of Nek5000.

I don't find it anywhere?

The current repo fails to build after I do git clone:

ld: warning: directory not found for option '-L/Users/fischer/Nek5000/3rd_party/gslib/lib'
ld: library not found for -lgs
collect2: error: ld returned 1 exit status
make: *** [nek5000] Error 1

Apparently, I need gslib.

When I go to the Nek5000 git page, there is no pointer to gslib - just Nekbone, NekExamples, etc.

How is one supposed to build from the repo?
What are all the steps??  Is it listed somewhere?

**Comment by stgeke** [comment]
It should just work.

On 20 May 2018, at 15:24, fischer1 <notifications@github.com <mailto:notifications@github.com> > wrote:

We should list gslib on the Nek5000 git page -- and we should provide, somewhere, full instructions on how to build the current repo version of Nek5000.

I don't find it anywhere?

The current repo fails to build after I do git clone:

ld: warning: directory not found for option '-L/Users/fischer/Nek5000/3rd_party/gslib/lib'
ld: library not found for -lgs
collect2: error: ld returned 1 exit status
make: *** [nek5000] Error 1

Apparently, I need gslib.

When I go to the Nek5000 git page, there is no pointer to gslib - just Nekbone, NekExamples, etc.

How is one supposed to build from the repo?
What are all the steps?? Is it listed somewhere?
