### ISSUE TITLE
Exo2Nek Sideset issue

### ISSUE THREAD

**Issue by yukkiezy** [Nek5000/Nek5000#502]
The sideset definition of exodus file from ICEM is not recognized in Exo2Nek. Exo2nek will assign sideset number again by itself regardless of the set up in ICEM. I guess it may has something to do with the key word in ICEM for sideset is SDSET which is different from what' defined in Exo2Nek.

**Comment by stgeke** [comment]
Can you please attach an example file generate with ICEM.

On 7 Jun 2018, at 11:13, yukkiezy <notifications@github.com <mailto:notifications@github.com> > wrote:

The sideset definition of exodus file from ICEM is not recognized in Exo2Nek. Exo2nek will assign sideset number again by itself regardless of the set up in ICEM. I guess it may has something to do with the key word in ICEM for sideset is SDSET which is different from what' defined in Exo2Nek.

**Comment by yukkiezy** [comment]
[sidesets.zip](https://github.com/Nek5000/Nek5000/files/2081420/sidesets.zip)
I attached a Hex20 exodus mesh file from ICEM for a tube. The sideset number defined in ICEM is 100 200 and 300 for inlet outlet and wall. It become 2 3 4 in Exo2nek.
Please let me know if more information is needed.

**Comment by yhaomin2007** [comment]
Hi, Yukkeizy,

there is some problem with current exo2nek recognize ICEM exo file sideset ID. 
exo2nek will assign your sideset to 2,3,4.... according to the time sequence you created sideset in ICEM boundary setting.

but exo2nek could recognize sideset ID correctly if your exo file is exported from CUBIT.
There must be some format difference between exo files exported from ICEM and CUBIT.

However, unfortunately we could access to ICEM source code to figure this out.

**Comment by yukkiezy** [comment]
Kirk,
I think you jump to the conclusion on exo2nek will assign your sideset according to the time sequence you created sideset in ICEM too soon. That's not right based on my test.
Yiqi

**Comment by ggiannako** [comment]
Converting your binary sidesets.exo to ascii using ncdump shows that indeed the sideset IDs defined are 2, 3, 4 (see attachment). This suggests that something goes wrong when exporting from ICEM. It is hard to believe that ICEM does not comply with the exodusII standard, are you sure you are performing the sideset definition/export step properly? (just a thought, not an ICEM expert)

[sidesets_ascii.tar.gz](https://github.com/Nek5000/Nek5000/files/2095951/sidesets_ascii.tar.gz)

**Comment by stgeke** [comment]
Are the IDs (exported by exonek) totally different or just shifted?

**Comment by yhaomin2007** [comment]
exo file exported from ICEM has totally different sideset number.
No matter what sideset number (1,2,3,4 or 1,4,3,2 or 4,2,3,1 ) you set in ICEM,  cubit/exo2nek cannot read correctly.
if you open one of the ICEM files *.fbc, you will see a sequence of all your sidesets you set in ICEM.
cubit/exo2nek will assign sideset 2,3,4... according to that sequence.

**Comment by yukkiezy** [comment]
The IDS is total different.
So I think there could be two possibility:
1. ncdump miss recognize the sideset ID from ICEM exported exodus,too. If that is the case, we still can do something on exo2nek side to solve this.
2. ICEM exported exodus actually does not contain any ID information assigned in ICEM. If that is the case, we can do nothing but inform ANSYS to fix their mesh output bugs.

**Comment by ggiannako** [comment]
Again, it is not a matter of the exo2nek conversion, the exodus file itself does not have the sideset IDs specified in ICEM (i.e. it contains IDs 2, 3, 4 instead of 100, 200, 300).

ncdump is part of the netCDF library and has nothing to do with exo2nek, it just converts the binary exodus to ascii.
 
How can exo2nek know the intended sideset IDs in ICEM if no information is passed to the exodus file?

**Comment by yhaomin2007** [comment]
We have a workaround to use exo file exported from ICEM.
I think it is not worthwhile to waste more time on this. 
We could not change the source code of ICEM.

**Comment by yhaomin2007** [comment]
However, it is good to add a note to exo2nek page to explain how to use exo2nek for ICEM exported exo file.

**Comment by stgeke** [comment]
What's the workaround?

-----Original message-----

**Comment by yhaomin2007** [comment]
if you open one of the ICEM files *.fbc, you will see a sequence of all your sidesets you set in ICEM.
cubit/exo2nek will assign sideset 2,3,4... according to that sequence.

**Comment by yukkiezy** [comment]
I think we are done with this issue for now. Just put some instruction on ICEM mesh exporting will work for release. .I will submit another issue on slow conversion with exo2nek for larger case as soon as I finished some test myself.

**Comment by stgeke** [comment]
Can we detect somehow that the exo file was exported from ICEM and read the fbc file. Just want to make it eady for the user. Other ideas are welcome!

**Comment by stgeke** [comment]
Prefered way for ICEM is to use the new cgns2nek converter.

**Comment by sethjdana** [comment]
How do we use cgns2nek converter?

**Comment by Zhonglu** [comment]
So I was using Ansys 2021 R1, ICEM, to do the exodus mesh. I guess I found a new bug that when I was having linear hybrid tetra + wedge mesh, the sideset ID starts to count from 3, 4, 5 ... rather than from 2, 3, 4 for the pure tetra mesh. I checked the source code that it is not an issue from exo2nek, but probably a matter of ICEM, since the official library of exodus is unlikely to be wrong. Again, I just feel strange. Will anyone recommend CUBIT above ICEM??

**Comment by Zhonglu** [comment]
Also, it seems ICEM cannot handle quadratic tetra10 + wedge15 mesh, causing an output error: 
![a7d746a72c559c32b88315faaff9cdd](https://github.com/Nek5000/Nek5000/assets/19511356/ae776ceb-7cba-45a8-a463-ef3c000d43a2)

Wondering if there is any solution for that?

**Comment by yukkiezy** [comment]
I think your observation may be right. There exists a bunch of bugs in ICEM. I would recommend to use. Fluent mesh tool over ICEM. For case that is simple, I would recommend cubit to make a script.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yhaomin2007** [comment]
In ICEM you cannot assign sidesets number directly. But you can trace the order of sideset from the .fbc file.

**Comment by yhaomin2007** [comment]
> Also, it seems ICEM cannot handle quadratic tetra10 + wedge15 mesh, causing an output error: ![a7d746a72c559c32b88315faaff9cdd](https://private-user-images.githubusercontent.com/19511356/341843576-ae776ceb-7cba-45a8-a463-ef3c000d43a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5OTQ3NzksIm5iZiI6MTcxODk5NDQ3OSwicGF0aCI6Ii8xOTUxMTM1Ni8zNDE4NDM1NzYtYWU3NzZjZWItN2NiYS00NWE4LWE0NjMtZWYzYzAwMGQ0M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE4Mjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNTdhMTI0Y2JlMzE4OTY3MjNhMDBmOGZhYTAyYzA1ZDQ3NDgyMWY3ZjE1ODhlMDFkYjM5MzdkZDdmZTllN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cKYbIgS7ZCooTC49BIHxkRJRLmcloWSNoQfpfDG8VfQ)
> 
> Wondering if there is any solution for that?
My ICEM (2021 R1) works fine with tet10 and wed15 meshes. But ICEM does have errors for exodus exporting if you do mirror operation on an existing tet10 and wed15 hybrid meshes.

**Comment by Zhonglu** [comment]
> Also, it seems ICEM cannot handle quadratic tetra10 + wedge15 mesh, causing an output error: ![a7d746a72c559c32b88315faaff9cdd](https://private-user-images.githubusercontent.com/19511356/341843576-ae776ceb-7cba-45a8-a463-ef3c000d43a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjYyMjIsIm5iZiI6MTcxOTA2NTkyMiwicGF0aCI6Ii8xOTUxMTM1Ni8zNDE4NDM1NzYtYWU3NzZjZWItN2NiYS00NWE4LWE0NjMtZWYzYzAwMGQ0M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE0MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5Njk5NTAxNTdjYzBiYWU0MDQ0NzAyMTM1MjVkNzhkMTY5YWZkOTZkMTk0ODhiMjUyNDlkMzhiYTMzZGM0MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.df5UBohrcc7yuXOcBHJ48Lw1HB-Ke6kAiMFRQMyrSZg)
> 
> Wondering if there is any solution for that?

Update: for this quadratic hybrid issue, I updated from ICEM 2021R1 to 2024R1, and this export error is no longer found, though I have not tested it further in nek. So it was a bug XD

**Comment by Zhonglu** [comment]
> I think your observation may be right. There exists a bunch of bugs in ICEM. I would recommend to use. Fluent mesh tool over ICEM. For case that is simple, I would recommend cubit to make a script. 

thx. I will probably try both fluent mesh and cubit. I also see some people got unstruct mesh by [Ansys Mesh](https://mooseframework.inl.gov/virtual_test_bed/htgr/httf/lower_plenum_cfd.html), being a bit confused which one to use.
