### ISSUE TITLE
ngeom > 2 for moving NekNek mesh stops at igeom = 3

### ISSUE THREAD

**Issue by kmittal2** [Nek5000/Nek5000#507]
At https://github.com/Nek5000/Nek5000/blob/master/core/drive2.f#L399, we generate mesh3 as long as it is not a moving NekNek case.. As a result, if we are doing ngeom > 2, this routine is not called and the simulation stops at igeom = 3. A better alternative would be to do:
`if (ifneknekm) return`
`CALL GENCOOR (XM3,YM3,ZM3)` ?

**Comment by stgeke** [comment]
@fischer1 What do you think?

I am also not sure how to support ngeom > 2 for passive scalars solved with CVODE.

**Comment by kmittal2** [comment]
#527

**Comment by stgeke** [comment]
Is this issue identical or only related to #527?

On 30 Aug 2018, at 18:52, k10 <notifications@github.com <mailto:notifications@github.com> > wrote:

#527

**Comment by kmittal2** [comment]
It is related to #527

**Comment by stgeke** [comment]
Can you please explain a little more in detail.

On 30 Aug 2018, at 19:16, k10 <notifications@github.com <mailto:notifications@github.com> > wrote:

It is related to #527

**Comment by kmittal2** [comment]
They are from the same routine, and issue 527 came up while discussing this issue.. I thought we could probably address them in the same PR.

**Comment by stgeke** [comment]
These are two different issues so let's treat them separately.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/33e565d03a6a3651402579d9a0911b589866575f
