### ISSUE TITLE
re2torea - unknown nel in buf_to_curve

### ISSUE THREAD

**Issue by GerritBotha** [Nek5000/Nek5000#511]
Hi Neks

Have been looking into converting large mesh .re2 to .rea. When outputting the rea file there is not enough space allocated for the element size. I have found than nel (the number of elements in the mesh) is not passed to buf_to_curve routine to determine the size of the format allocation.

Regards

**Comment by fischer1** [comment]
Gerrit,

How large?

________________________________

**Comment by GerritBotha** [comment]
Paul

At the moment +200K elements.

In re2torea.f there is a check that changes the format depending on the size of nel, the first is nel<1000, but nel is never passed, so it always defaults to the smallest format.

**Comment by stgeke** [comment]
Good catch Gerrit! Indeed nel is unknown in buf_to_curve().
