### ISSUE TITLE
Add support for different relative tolerance in each CVODE scalar

### ISSUE THREAD

**Issue by ggiannako** [Nek5000/Nek5000#513]

**Comment by stgeke** [comment]
This is not supported by CVODE (at least in the version we're using).

**Comment by ggiannako** [comment]
For low-Ma + dp/dt cases, using a relTol=1e-06 we get a significant (accumulating) error in mass. To compute the correct p0th (and, as a consequence rho=p0th/temp) we need to set relTol to at least 1e-08, which is obviously VERY expensive for production runs. 

According to the CVODE v.2.9.0 manual, it looks to me that we can directly specify a vector containing the weights in the WRMS norm instead of relTol and absTol_i (see p.27 and p.65), no?

**Comment by stgeke** [comment]
Turns out that this approach didn't work out.
