### ISSUE TITLE
Capability of Nek5000

### ISSUE THREAD

**Issue by AjitPanja** [Nek5000/Nek5000#515]
Hello. I am completely new to nek5000. I have some queries regarding the capability of this open source spectral code. Is nek5000 capable of simulating isothermal turbulent mixing of two fluids? Is it also capable of simulations with variable fluid  property? Thanks in advance.

**Comment by stgeke** [comment]
Please use our mailing list for question like this. For more informations see DOCS->FAQ on our webpage.
