### ISSUE TITLE
get_unit(): Bad internal unit KIND

### ISSUE THREAD

**Issue by KennellyT** [Nek5000/Nek5000#518]
Hey,
I recently downloaded and installed nek5000 onto my computer and tried to run a example [case](https://nek5000.mcs.anl.gov/files/2015/09/NEK_doc.pdf). After calling:
./nekbmpi eddy_uv 2
I received:
mv: cannot stat 'eddy_uv.log.2': No such file or directory
mv: cannot stat 'eddy_uv.sch': No such file or directory
At line 349 of file /home/tyler/nek5_svn/trunk/nek/connect2.f
Internal Error: get_unit(): Bad internal unit KIND
At line 349 of file /home/tyler/nek5_svn/trunk/nek/connect2.f
Internal Error: get_unit(): Bad internal unit KIND
I was wondering if I did not install NEK5000 correctly?
Thank you

**Comment by stgeke** [comment]
It looks like this is an old svn version? Make sure you download the latest release from our website available at https://nek5000.mcs.anl.gov

**Comment by KennellyT** [comment]
Hey @stgeke,
After unistalling the old svn version of Nek5000, I followed the instructions via the instructions. I was able to reach:
`nekbmpi eddy_uv 2`
where received this error:
`At line 171 of file /home/tyler/Nek5000/core/reader_rea.f`
`Internal Error: get_unit(): Bad internal unit KIND`
`At line 171 of file /home/tyler/Nek5000/core/reader_rea.f`
`Internal Error: get_unit(): Bad internal unit KIND`
After looking online, this seems to be a complier issue with gcc, g, and gfortran version 5+.
I'll see if changing gcc, g, and gfortran to version 4 helps

**Comment by KennellyT** [comment]
Update: After moving my gcc, g, and gfortran versions to 4.8, the error still occurs.

**Comment by stgeke** [comment]
Can you try again with a more recent version e.g gcc v6.x

**Comment by anshchaube** [comment]
@stgeke This error occurs with gcc 6.4 as well

**Comment by stgeke** [comment]
Hmm ... I was not able to reproduce this with 6.2. Can you please tell me more (OS, MPI, ...) about your system.

**Comment by anshchaube** [comment]
OS - Ubuntu 16.04
gfortran version - 5.4.0
mpich - 3.2-6build1
HYDRA build details:
    Version:                                 1.4.1p1

**Comment by stgeke** [comment]
You're using gfortran 5.4 but you tried 6.4 as well right?

**Comment by anshchaube** [comment]
Yes, I tried it with 6.4, 7.3, 4.8 and 4.4. Got the same error.

**Comment by anshchaube** [comment]
With gfortran 8.1 I get the following after running genmap:
`Segmentation fault (core dumped)`

**Comment by stgeke** [comment]
Hmm 6.4 works for me. Are you using mpif77 to compile Nek5000? Can you please double check that the MPI wrapper does indeed use the right compiler version.

On 6 Aug 2018, at 20:05, Ansh Chaube <notifications@github.com <mailto:notifications@github.com> > wrote:

Yes, I tried it with 6.4 and 7.3. Got the same error.

**Comment by stgeke** [comment]
Please add a new issue for this.

On 6 Aug 2018, at 20:25, Ansh Chaube <notifications@github.com <mailto:notifications@github.com> > wrote:

With gfortran 8.1 I get the following after running genmap:
Segmentation fault (core dumped)

**Comment by anshchaube** [comment]
Not sure if this provides all the information you need, but I ran the following command: `mpif77 -v` and I got:

```
mpif77 for MPICH2 version 1.4.1p1
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.4.0-17ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --with-as=/usr/bin/x86_64-linux-gnu-as --with-ld=/usr/bin/x86_64-linux-gnu-ld --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.4.0 20180424 (Ubuntu 6.4.0-17ubuntu1~16.04)  ```

**Comment by stgeke** [comment]
What eddy case is this? The one in short_tests?
Can you please run e.g. Nek5000/short_tests/ethier and tell me if this works for you.

**Comment by anshchaube** [comment]
The problem seems to have been caused by a mismatch in gfortran, gcc and g++ versions. Changing them all to v7 fixed the problem. I think #524 is caused by this as well.

**Comment by stgeke** [comment]
Thanks for the update.

**Comment by zyupcqingdao** [comment]
I have encountered the same problem, how can I solve it?
