### ISSUE TITLE
Reading input files in parallel

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#52]
A case with 4M elements and AMG needs more than 15min (on BGQ) to initialize. This is due to the poor I/O performance reading the input files (.re2, .map, AMG files) on MPI_RANK_0 only. A parallel-read would speed up things quite a bit.

**Comment by stgeke** [comment]
@emerzari reported that reading a 15M element re2 file (with lots of curved sides) took about 40min.

**Comment by stgeke** [comment]
The slow performance is related to the fact that we issue a `read()` and `send()` for every curved/bc data-item (32 bytes). Instead we should read the data in big blocks and crystal route the data. This will improve the performance significantly even if we don't read-in the data in parallel.

**Comment by stgeke** [comment]
@fischer1 Why was it implement like this. Am I missing something?

**Comment by fischer1** [comment]
Probably just implemented in a dumb way...  I'll try to look later this eve.

________________________________

**Comment by stgeke** [comment]
Most time consuming .re2 reader was parallelized in @ #203
