### ISSUE TITLE
double precision in avg_out

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#522]
Should we default to real*8 output for the avg/rms/rm2 files?

It seems that the truncation of  <u^2> and <u> to 32-bit can lead to negative variances
on the order of -1.e-7 when computing

  <u^2> - <u>^2

as a postprocessing step.

Here is an example of how a user could do it, but probably better to do it inside avg_all?

c     Turbulence statistics

      iastep    = 50

      param(68) = iastep

      if (istep.gt.0.and. mod(istep,iastep).eq.0) param(63) = 1 ! 64-bit avg
      call avg_all
      param(63) = 0 ! Set output wordsize back to 32-bit

**Comment by pschlatt1** [comment]
I would clearly say yes. In our 2D and 3D version of the statistics we use real*8.

**Comment by stgeke** [comment]
Implement in #520
