### ISSUE TITLE
Bug in drive2.f w.r.t. igeom=3 and dssum(xm3, etc)

### ISSUE THREAD

**Issue by fischer1** [Nek5000/Nek5000#527]
There is a piece of ancient code (from at least 2008) in drive2.f where there is 
dssum(xm3, ...), etc.    It should be deleted --- you cannot dssum geometry because
geometry is not a periodic function.  (This code generated by pff prior to 2008...probably
for some one-off need...)

Here are the lines that should be deleted

         if (ifheat) then
            ifield = 2
            CALL dssum(xm3,lx3,ly3,lz3)
            call col2 (xm3,tmult,ntot3)
            CALL dssum(ym3,lx3,ly3,lz3)
            call col2 (ym3,tmult,ntot3)
            if (if3d) then
               CALL dssum(xm3,lx3,ly3,lz3)
               call col2 (xm3,tmult,ntot3)
            endif
         else
            ifield = 1
            CALL dssum(xm3,lx3,ly3,lz3)
            call col2 (xm3,vmult,ntot3)
            CALL dssum(ym3,lx3,ly3,lz3)
            call col2 (ym3,vmult,ntot3)
            if (if3d) then
               CALL dssum(xm3,lx3,ly3,lz3)
               call col2 (xm3,vmult,ntot3)
            endif
         endif

**Comment by stgeke** [comment]
Fixed in #520
