### ISSUE TITLE
ms_glsc2 returning integer

### ISSUE THREAD

**Issue by kmittal2** [Nek5000/Nek5000#529]
I have noticed on my mac that ms_glsc2 returns an integer even if I declare the variable (output) and the function (ms_glsc2) as real. [https://github.com/Nek5000/Nek5000/blob/master/core/math.f#L1688](url)

For example:
if I have the following functions in math.f:
`      real function ms_glsc2(a,b,n)`
`      include 'SIZE'`
`      real a(1),b(1)`

`      call setnekcomm(iglobalcomm)`
`      ms_glsc2 = glsc2(a,b,n)`
`      call setnekcomm(intracomm)`

`      return`
`      end`
`c-----------------------------------------------------------------------`
`      real function uglsc2(a,b,n)`
`      include 'SIZE'`
`      real a(1),b(1)`

`      call setnekcomm(iglobalcomm)`
`      uglsc2 = glsc2(a,b,n)`
`      call setnekcomm(intracomm)`

`      return`
`      end`

The output is what I expect from uglsc2 but 0 from ms_glsc2 when I do `uvol = uglsc2(vz,bmg,nv)` versus `uvol = ms_glsc2(vz,bmg,nv)` even though `uvol` is defined as `real` in the `.usr` file. Should we rename these functions?

**Comment by stgeke** [comment]
For the moment you have to define ms_glsc2 as real wherever it’s getting used. We will explicitly define all functions through SIZE.inc in all future releases.

On 30 Aug 2018, at 18:52, k10 <notifications@github.com <mailto:notifications@github.com> > wrote:

I have noticed on my mac that ms_glsc2 returns an integer even if I declare the variable (output) and the function (ms_glsc2) as real. https://github.com/Nek5000/Nek5000/blob/master/core/math.f#L1688

For example:
if I have the following functions in math.f:
real function ms_glsc2(a,b,n)
include 'SIZE'
real a(1),b(1)

call setnekcomm(iglobalcomm)
ms_glsc2 = glsc2(a,b,n)
call setnekcomm(intracomm)

return
end
c-----------------------------------------------------------------------
real function uglsc2(a,b,n)
include 'SIZE'
real a(1),b(1)

call setnekcomm(iglobalcomm)
uglsc2 = glsc2(a,b,n)
call setnekcomm(intracomm)

return
end

The output is what I expect from uglsc2 but 0 from ms_glsc2 when I do uvol = uglsc2(vz,bmg,nv) versus uvol = ms_glsc2(vz,bmg,nv) even though uvol is defined as real in the .usr file. Should we rename these functions?

**Comment by stgeke** [comment]
Looks like those functions are already defined in PARALLEL. Did you include PARALLEL?

**Comment by kmittal2** [comment]
Yes, I had included Total which includes Parallel.

Ketan

________________________________

**Comment by stgeke** [comment]
Fixed in #520
