### ISSUE TITLE
usrdiv being added to qtl in pn-pn for all igeom > 1

### ISSUE THREAD

**Issue by kmittal2** [Nek5000/Nek5000#532]
In Plan4 (https://github.com/Nek5000/Nek5000/blob/master/core/plan4.f#L55): 'call add2 (qtl,usrdiv,ntot1)' for all igeom > 1. In a case with non-zero usrdiv and ngeom > 2, this will keep adding usrdiv to qtl. One specific case that comes to mind is when ngeom > 2 and  turb_Outflow is called in userchk.

**Comment by kmittal2** [comment]
We should be zeroing out qtl at all igeom > 2
https://github.com/Nek5000/Nek5000/blob/master/core/drive1.f#L318

**Comment by stgeke** [comment]
Fixed
