### ISSUE TITLE
missing gs-handle setup for DG 

### ISSUE THREAD

**Issue by misunmin** [Nek5000/Nek5000#533]
call fgslib_gs_op(dg_hndlx,uf,1,1,0)  ! 1 ==> +  :   uf <-- uf^- + uf^+

Seems we are missing setup routine for dg_hndlx.

**Comment by stgeke** [comment]
In dg_setup()

`call setup_dg_gs(dg_hndlx,lx1,ly1,lz1,nelt,nelgt,vertex)`

we set the handle. Am I missing something?
