### ISSUE TITLE
use runtime parameter for max iteration counts for each field

### ISSUE THREAD

**Issue by misunmin** [Nek5000/Nek5000#534]
Flexibly assigning "max iteration #" possible for each field, provided by the user (either static or time-varying in usr file, not as param) instead of the following :

In drive2.f:     
 -- line 190       NMXH   = 1000
 -- line 191       if (iftran) NMXH   = 100

ps: Initiated with Yu-Hsiang and developed primary discussion with P. F.

**Comment by stgeke** [comment]
Implemented in #557
