### ISSUE TITLE
Restart accuracy issues

### ISSUE THREAD

**Issue by misunmin** [Nek5000/Nek5000#535]

**Comment by stgeke** [comment]
- [ ]  Put LAGPRES with LAGVEL at cresvif: PNPN-2 + full restart + RANS (nonlinear source term) in planx.f
- [ ] Remove `if_full_pres = .false.` in restart_save()
- [ ] Do not dssum at the end of setics()

**Comment by stgeke** [comment]
Resolved in latest master
