### ISSUE TITLE
exo2nek error: Increase MAXNEL and compile error

### ISSUE THREAD

**Issue by rajeeja** [Nek5000/Nek5000#538]
I changed the maketools file to increase MAXNEL. 
diff --git a/tools/maketools b/tools/maketools
index ea425e0..3d6ace9 100755
--- a/tools/maketools
+++ b/tools/maketools
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # maximum number of elements
-#MAXNEL=150000
+MAXNEL=850000

Now compiling the tool, I get this error:

```

           call chcopy (buf2(8),ch3,3)                                 
                         1
Warning: Type mismatch in argument 'a' at (1); passed REAL(8) to CHARACTER(1)
/usr/bin/gcc -c  -DUNDERSCORE -mcmodel=medium ../../core/byte.c
/usr/bin/gfortran -c -DMAXNEL=850000 -std=legacy -cpp -mcmodel=medium -fdefault-real-8 -fdefault-double-8 ../../core/speclib.f
/usr/bin/gfortran -c -DMAXNEL=850000 -std=legacy -cpp -mcmodel=medium -fdefault-real-8 -fdefault-double-8 mxm.f
/usr/bin/gfortran -DMAXNEL=850000 -std=legacy -cpp -mcmodel=medium -fdefault-real-8 -fdefault-double-8 -o /homes/jain/exo2nek_Nek5000/bin/exo2nek exo2nek.o byte.o speclib.o mxm.o ./3rd_party/seacas-exodus/build/packages/seacas/libraries/exoIIv2for32/libexoIIv2for32.a ./3rd_party/seacas-exodus/build/packages/seacas/libraries/exodus/libexodus.a ./3rd_party/netcdf/install/lib/libnetcdf.a 
./3rd_party/netcdf/install/lib/libnetcdf.a(libdispatch_la-dutf8proc.o): In function `utf8proc_get_property':
dutf8proc.c:(.text+0x4a3): relocation truncated to fit: R_X86_64_PC32 against symbol `utf8proc_properties' defined in .ldata.rel.ro section in ./3rd_party/netcdf/install/lib/libnetcdf.a(libdispatch_la-dutf8proc.o)
./3rd_party/netcdf/install/lib/libnetcdf.a(libdispatch_la-dutf8proc.o): In function `utf8proc_reencode':
dutf8proc.c:(.text+0x13cd): relocation truncated to fit: R_X86_64_PC32 against symbol `utf8proc_combinations' defined in .lrodata section in ./3rd_party/netcdf/install/lib/libnetcdf.a(libdispatch_la-dutf8proc.o)
collect2: error: ld returned 1 exit status
make[1]: *** [exo2nek] Error 1
make[1]: Leaving directory `/nfs2/jain/exo2nek_Nek5000/tools/exo2nek'

ERROR: exo2nek failed to compile!

An unexpected error occurred while compiling!
make: *** [all] Error 1

```

It seems like if the code is already compiled and recompiled, there is no error -> but the actual change of MAXNEL is not in effect as this change has to be in NetCDF. 

The problem  more netcdf flags changes are needed:
https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/268374

**Comment by stgeke** [comment]
The .text section seems to exceed the 2GB limit, so you have to compile with mcmodel=large. We will fix this differently in the next release.

**Comment by eklunm** [comment]
I tried doing this on Nek5000 v-17.0 release. I changed the lines in the "maketools" script to "mcmodel=large" and "MAXNEL=1000000" and tried compiling. It appears it finished compiling, but when i tried to run the exo2nek tool, it just gave this output:

$ ~/2018-10-03-Nek-Install/Nek5000-v17.0/bin/exo2nek 
Killed

Do you know why this might be the case? Is "MAXNEL=1000000" too large?

Thanks.

**Comment by eklunm** [comment]
I was able to get it to compile by setting "MAXNEL=780000" and work correctly. Maybe some numbers are too high, or sometimes it doesn't compile correctly. Not sure. But it works now.

**Comment by stgeke** [comment]
The program was probably killed by your OS because some limits (e.g. process's data segment) were exceeded. For now you have to lower MAXNE.
