### ISSUE TITLE
exo2nek fail to build with laster master

### ISSUE THREAD

**Issue by eklunm** [Nek5000/Nek5000#539]
I haven't been able to correctly compile the "exo2nek" script in the "tools" folder.

I tried running "./maketools exo2nek" as is instructed, using gcc, but it never compiles correctly. It originally said my version of CMake was too low, so I downloaded and installed CMake 3.12.2, and the error disappeared. However, the script still refuses to completely compile, and I don't know what is causing the error. This is using the latest Nek5000 version.

I was attempting to compile using the GNU compilers (gcc, g++) v. 4.8.4. The output from the terminal is included. Thank you.
[exo2nek_compile_errors.txt](https://github.com/Nek5000/Nek5000/files/2452136/exo2nek_compile_errors.txt)

**Comment by stgeke** [comment]
The build is broken (because of upstream changes) in master. Please use the release v17 instead.

-----Original message-----

**Comment by stgeke** [comment]
https://github.com/gsjaardema/seacas

**Comment by stgeke** [comment]
Fixed in #557
