### ISSUE TITLE
Error in "genmap" Script

### ISSUE THREAD

**Issue by eklunm** [Nek5000/Nek5000#542]
I am attempting to use the "genmap" script in the Nek5000 v. 17.0 release for a .re2 file that I converted using the "exo2nek" script from an Exodus II mesh file. However, no matter what mesh tolerance settings I use (1E-19 to > 1), it never completes correctly. Do you have any information why this would occur? Thanks.

Below is an example of the output I am seeing:

 $ ../../2018-10-17-Nek5000-v170/Nek5000/bin/genmap
Input .rea / .re2 name:
RCF_Pipe_180kEl
 reading RCF_Pipe_180kEl.re2                                                             
Input mesh tolerance (default 0.2):
NOTE: smaller is better, but generous is more forgiving for bad meshes.
0.7
 reading mesh data ...
 start locglob_lexico:           8      151220     1209760  0.69999999999999996     
 locglob:           1           1     1209760
 locglob:           2          15     1209760
 locglob:           3         494     1209760
 locglob:           1       15825     1209760
 locglob:           2       41473     1209760
 locglob:           3       63370     1209760
 locglob:           1       63575     1209760
 locglob:           2       74864     1209760
 locglob:           3       79320     1209760

    11     2     4  Matrix:  SELF!!
       1 SELF!!    53490    53489    53490    53487
       2 SELF!!    53478    53477    53478    53474
 cont: SELF!!          11

 ABORT: SELF-CHK            1           5          11           0
 Try to tighten the mesh tolerance!

           0  quit

**Comment by stgeke** [comment]
Please post your problem on the mailing list. I don’t think this is a genmap bug.

On 17 Oct 2018, at 21:59, eklunm <notifications@github.com <mailto:notifications@github.com> > wrote:

I am attempting to use the "genmap" script in the Nek5000 v. 17.0 release for a .re2 file that I converted using the "exo2nek" script from an Exodus II mesh file. However, no matter what mesh tolerance settings I use (1E-19 to > 1), it never completes correctly. Do you have any information why this would occur? Thanks.

Below is an example of the output I am seeing:

$ ../../2018-10-17-Nek5000-v170/Nek5000/bin/genmap
Input .rea / .re2 name:
RCF_Pipe_180kEl
reading RCF_Pipe_180kEl.re2
Input mesh tolerance (default 0.2):
NOTE: smaller is better, but generous is more forgiving for bad meshes.
0.7
reading mesh data ...
start locglob_lexico: 8 151220 1209760 0.69999999999999996
locglob: 1 1 1209760
locglob: 2 15 1209760
locglob: 3 494 1209760
locglob: 1 15825 1209760
locglob: 2 41473 1209760
locglob: 3 63370 1209760
locglob: 1 63575 1209760
locglob: 2 74864 1209760
locglob: 3 79320 1209760


11     2     4  Matrix:  SELF!!
   1 SELF!!    53490    53489    53490    53487
   2 SELF!!    53478    53477    53478    53474


cont: SELF!! 11

ABORT: SELF-CHK 1 5 11 0
Try to tighten the mesh tolerance!


       0  quit
