### ISSUE TITLE
Run serial Travis tests w/o MPI

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#55]
Right now, all the Travis tests are compiled and run with MPI.  That is, they are compiled with mpif77/mpicc and run with mpiexec.  For the serial tests, we simply run with `mpiexec -np 1`.

In Nek5000/NekExamples#15, @stgeke suggested that we compile/run serial tests without MPI.

**Comment by stgeke** [comment]
@RonRahaman Can we close this?

**Comment by RonRahaman** [comment]
No, PR #82 hasn't been merged yet

**Comment by RonRahaman** [comment]
@stgeke, could you check on #82 and confirm if it can be approved?

**Comment by RonRahaman** [comment]
Merged in PR #82
