### ISSUE TITLE
 dt variable that is not the timestep

### ISSUE THREAD

**Issue by nicooff** [Nek5000/Nek5000#559]
https://github.com/Nek5000/Nek5000/blob/469daf94d3f9aa3ba9d258d8eee9ebde6893a702/core/map2.f#L92

In function `mapelpr`, a variable `dt` is defined but is not the timestep (just a timer). Since TSTEP is included in the subroutine, the actual timestep is replaced by this somehow random value. We've encountered some issues with this. The variable should be renamed. Also, is it necessary to include TSTEP?

**Comment by stgeke** [comment]
Thanks for catching this. Will rename the variable. 

-----Original message-----

**Comment by nicooff** [comment]
Thanks!

**Comment by stgeke** [comment]
Fixed in #557
