### ISSUE TITLE
gslib v1.0.3 problems: deleted header

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#560]
We're getting some build errors with the master branch.  Looks like `fcrs.c` depends on the `crs.h` file:
https://github.com/Nek5000/Nek5000/blob/a2fd3edeaa8ac8410ba86f9b5d2917ae2a444432/core/fcrs.c#L11

But that was removed in gslib v1.0.3
https://github.com/gslib/gslib/commit/f70e2fcf7e21209fbcb433a5068c5adcaa4a970c#diff-b862fc63d22c3c7b4f6ede0a7e6175b5

**Comment by RonRahaman** [comment]
Looks like this didn't show up in Nek5000's CI tests because crs.h was removed from gslib on Dec 1, but the last time Nek5000 was updated was Sept 20.

**Comment by stgeke** [comment]
That's because of a change in gslib 1.0.3 (which is a pre-release) breaking the latest master. I will fix this in the next few hours.

**Comment by stgeke** [comment]
Fixed in latest master
