### ISSUE TITLE
Maketools with GCC 8

### ISSUE THREAD

**Issue by jeremylt** [Nek5000/Nek5000#563]
While running maketools genmap for OSX Travis, I discovered that the FFlags list for maketools does not include -std=legacy:
/usr/local/bin/gfortran -c -DMAXNEL=150000 -cpp  -fdefault-real-8 genmap.f

This causes maketools to error out on Travis's OSX env when gcc 8 is installed (and probably elsewhere as well).

Travis Error Here: https://travis-ci.org/CEED/libCEED/jobs/466238703

Nek5k Version: V17.0

**Comment by stgeke** [comment]
This is fixed in the latest master.

**Comment by jeremylt** [comment]
Thank you
