### ISSUE TITLE
Using lxd=lx1 breaks ethier on BGQ

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#565]
* This happens only with the IBM compiler on BGQ
* Compiling set_dealias_rx() without any optimizations (O0) seems to fix the problem

This might be related to a "bigger" issue.

**Comment by trudeaun** [comment]
Sorry to hear about this! Please [open a PMR](https://www-947.ibm.com/support/servicerequest/newServiceRequest.action) with IBM and the support team will help you out.

**Comment by stgeke** [comment]
https://github.com/Nek5000/Nek5000/commit/664af068866e2f41ac173459e9999d1abfafc5c5
