### ISSUE TITLE
Compilation fails because reference to MPI_Attr_get was not found.

### ISSUE THREAD

**Issue by stgeke** [Nek5000/Nek5000#585]
This seems to happen e.g. with OpenMPI 4.0.0.
Note, MPI_Attr_get() was deleted in MPI-3.

**Comment by fischer1** [comment]
Is there a replacement in MPI 4 ?

**Comment by stgeke** [comment]
There is one in MPI-2 but we still using the deprecated one from MPI-1. I will update it.

On 9 Jan 2019, at 23:48, fischer1 <notifications@github.com <mailto:notifications@github.com> > wrote:

Is there a replacement in MPI 4 ?

**Comment by stgeke** [comment]
Fixed
