### ISSUE TITLE
ifcomp possibly not uniform over processes

### ISSUE THREAD

**Issue by nicooff** [Nek5000/Nek5000#600]
In subroutine `vol_flow`, the variable `ifcomp` could potentially be different on different processes, which causes the code to hang. A call to `gllog` should fix that.

https://github.com/Nek5000/Nek5000/blob/48284bda5206f6bb3258deef6c1e3e20ecd88cee/core/drive2.f#L1433-L1443

**Comment by stgeke** [comment]
How can ifcomp be different?

**Comment by nicooff** [comment]
In the case vdiff or vtrans are modified locally, ifcomp would be true on processes where these arrays have been modified and it would be false otherwise.
