### ISSUE TITLE
makenek not passing user flags

### ISSUE THREAD

**Issue by jeremylt** [Nek5000/Nek5000#610]
During one of the commits in the last day, `makenek` stopped passing and using user flags.

To replicate, attempt to build the Nek5000 examples in libCEED.

Building fails with the message
```
/home/jeremy/Dev/libceed/examples/nek5000/bp1.f:692: Error: Can't open included file 'ceedf.h'
```

The proper include directory was passed when @thilinarmtb set up the bash script to make these examples however:
```
sed -i.bak -e "s|^#FC=.*|FC=\"$FC\"|" \
    -e "s|^#CC=.*|CC=\"$CC\"|" \
    -e "s|^#NEK_SOURCE_ROOT=.*|NEK_SOURCE_ROOT=\"${NEK5K_DIR}\"|" \
    -e "s|^#FFLAGS=.*|FFLAGS+=\"-g -std=legacy -I${CEED_DIR}/include\"|" \
    -e "s|^#USR_LFLAGS+=.*|USR_LFLAGS+=\"-g -L${CEED_DIR}/lib -Wl,-rpath,${CEED_DIR}/lib -lceed\"|" makenek
```

The correct flags are making their way into `makenek`
```
# optional compiler flags
FFLAGS+="-g -std=legacy -I/home/jeremy/Dev/libceed/include"
#CFLAGS=""

# optional linking flags
USR_LFLAGS+="-g -L/home/jeremy/Dev/libceed/lib -Wl,-rpath,/home/jeremy/Dev/libceed/lib -lceed"
```

but they are not being used by the `makefile`
`bp1.build.log` output:
```
mpif77  -O2 -std=legacy -fdefault-real-8 -fdefault-double-8 -cpp -DMPI -DUNDERSCORE -DGLOBAL_LONG_LONG -DTIMER -I/home/jeremy/Dev/libceed/examples/nek5000 -I/home/jeremy/Dev/Nek5000/core -I./ -I /home/jeremy/Dev/Nek5000/core/experimental  -c /home/jeremy/Dev/libceed/examples/nek5000/bp1.f
```

**Comment by thilinarmtb** [comment]
Okay, yes, this is a recent change in master and we need to fix this.

If it is urgent, please fix Nek5000 at a commit that works in the current
setting.

Will push a fix later.

Regards,
Thilina

**Comment by stgeke** [comment]
Fixed with https://github.com/Nek5000/Nek5000/commit/30122963c98e902e1969293d7e919785423e64d2

**Comment by jeremylt** [comment]
Thank you
