### ISSUE TITLE
makenek compile issue

### ISSUE THREAD

**Issue by HaochenCFD** [Nek5000/Nek5000#618]
Hi,

I successfully compile "makenek" for the newest release of v19.0-rc2 under the configuration of:
mpif77  -O2 -cpp -fdefault-real-8 -fdefault-double-8 -std=legacy  -DMPI -DUNDERSCORE -DGLOBAL_LONG_LONG -DTIMER 

However, when I use the following configuration, it will give undefined reference error.
mpif77  -O2 -fpp -r8 -fpconstant   -DMPI -DUNDERSCORE -DGLOBAL_LONG_LONG -DTIMER

/Nek5000/3rd_party/blasLapack/libblasLapack.a(dlamch.o): In function `dlamc2_':
dlamch.f:(.text+0x734): undefined reference to `_gfortran_st_write'
dlamch.f:(.text+0x748): undefined reference to `_gfortran_transfer_integer_write'
dlamch.f:(.text+0x750): undefined reference to `_gfortran_st_write_done'
dlamch.f:(.text+0xa23): undefined reference to `_gfortran_st_write'
dlamch.f:(.text+0xa37): undefined reference to `_gfortran_transfer_integer_write'
dlamch.f:(.text+0xa3f): undefined reference to `_gfortran_st_write_done'

Any guidance is appreciated.
Thanks,
Rdf

**Comment by stgeke** [comment]
Did you change compilers? It looks like blasLapck was compiled with GNU but now you're using a different compiler so it cannot find the GNU runtime libs. Please run ./makenek clean (delete 3rd-party deps) and try again. 

-----Original message-----

**Comment by HaochenCFD** [comment]
Stefan,

You are right. No problem with mpif77 -O2 -fpp -r8 -fpconstant -DMPI -DUNDERSCORE -DGLOBAL_LONG_LONG -DTIMER after clean the third party and recompile.

Thank you,
Rdf
