### ISSUE TITLE
mg_lmax is not set in h1mg_setup_mg_nx

### ISSUE THREAD

**Issue by yslan** [Nek5000/Nek5000#619]
We set the mg_h1_lmax in the subroutine, h1mg_setup_mg_nx, but we use mg_lmax in the later loop. The code still works because mg_lmax is global and being set in other subroutine, hsmg_setup_mg_nx.

https://github.com/Nek5000/Nek5000/blob/faeaa56d2f43ec64c1a0e0fa1363498796d0df8a/core/hsmg.f#L2291-L2294

https://github.com/Nek5000/Nek5000/blob/faeaa56d2f43ec64c1a0e0fa1363498796d0df8a/core/hsmg.f#L2329

**Comment by stgeke** [comment]
Can you please provide a PR fixing this. 

-----Original message-----
