### ISSUE TITLE
simulating full axisymmetric pipe

### ISSUE THREAD

**Issue by Platinumd1991** [Nek5000/Nek5000#621]
Hi,

I am trying to simulate a full pipe (D=1) using the axi example in the Nek directory. I have made my own box using genbox expanding the y axis from 0 to 0.5 into -0.5 to 0.5 for a full pipe. The problem is I get NaNs for my solution but it completes the runs with incorrect solution. When I run the same condition with the original axi file, it works fine with no NaNs. Please help! I am super new to Nek5000 and I am sure I compiled it correctly but still doesn't work!

**Comment by stgeke** [comment]
Please use the mailing list for request like this.

**Comment by Platinumd1991** [comment]
Hi Stefan,

I clicked to join the google group but so far my membership is pending,
could I be approved so I can post things like this? I've tried to use the
mailing list given online but I always received back that my email did not
send. I would appreciate your help.

Thank you
