### ISSUE TITLE
Error on following Quickstart Instructions

### ISSUE THREAD

**Issue by navdeeprana** [Nek5000/Nek5000#626]
On following quickstart instructions given [here](http://nek5000.github.io/NekDoc/quickstart.html#running-your-very-first-simulation)
I end up with the following error:

    Error: Actual argument contains too few elements for dummy argument ‘p’ (1/2) at (1)
    make[1]: *** [makefile:13: genmap.o] Error 1
    make[1]: Leaving directory '/home/rana/Downloads/Nek5000/tools/genmap'

    ERROR: genmap failed to compile!
Edit

Works with `gcc 4.8.5`, Error comes up with `gcc 9.1.1`

**Comment by stgeke** [comment]
Is this with the latest master or release v17?

**Comment by navdeeprana** [comment]
Release v17

**Comment by stgeke** [comment]
Only latest master supports GCC >v7.

**Comment by navdeeprana** [comment]
Oh okay. Thanks for the clarification. I got it working with older version
of GCC.
