### ISSUE TITLE
Creating .rea file 

### ISSUE THREAD

**Issue by sandip076** [Nek5000/Nek5000#631]
I am very beginner in Nek5000.
My box file is

-22 8                                              Nelx Nely
0.0 9.0 1.                                         x0 x1 ratio
0.0 0.1 0.25 0.5 1.5 2.5 2.75 2.9 3.0              y0 y1 ratio
u  ,u  ,W  ,W                                  BC's: (cbx0, cbx1, cby0, cby1)
I want to generate .rea, how can I create .rea file.

**Comment by stgeke** [comment]
Please use the mailing list for request like this.
