### ISSUE TITLE
Option to reduce logfile output

### ISSUE THREAD

**Issue by lcarasik** [Nek5000/Nek5000#633]
Currently, there does not seem to be an option to reduce the verbosity of the basic output file. For very long runs this causes the logfile to get excessively long and can cause storage issues for some of us. 

I imagine this would leverage the loglevel option in the Par file and would involve something to the effect of reducing the number of printed out time-steps to a user specified amount.

**Comment by stgeke** [comment]
You should be able to set nio to -1 in usrchk to suppress stdout.

On 24 Jun 2019, at 20:18, Lane Carasik <notifications@github.com <mailto:notifications@github.com> > wrote:

Currently, there does not seem to be an option to reduce the verbosity of the basic output file. For very long runs this causes the logfile to get excessively long and can cause storage issues for some of us.

I imagine this would leverage the loglevel option in the Par file and would involve something to the effect of reducing the number of printed out time-steps to a user specified amount.

**Comment by lcarasik** [comment]
Doesn't that suppress all logfile output?

**Comment by stgeke** [comment]
You can turn it on and off in userchk every N steps?

On 24 Jun 2019, at 21:37, Lane Carasik <notifications@github.com <mailto:notifications@github.com> > wrote:

Doesn't that suppress all logfile output?

**Comment by fischer1** [comment]
Hi Lane,


I often do the following in userchk:



      nio = -1

      if (istep.le.100.or.mod(istep,10).eq.0) nio=nid


That will turn off virtually all i/o (save to the .f000 files) for 9 out of 10 steps.


Modify to suit...


Cheers,
Paul


________________________________

**Comment by lcarasik** [comment]
Thanks all I'll use this, but I still think it would be useful to add it as a feature through the .par file.

**Comment by fischer1** [comment]
Hi Lane,


That would be possible, if we had an agreed upon interface/use-model.


I like the model of the preceding email --- verbose at the beginning, barely

verbose once things are cruising along.


I wouldn't know how to prescribe that in the .par file --- but I guess we

could do something like:


io_on:  istep < 100

io_on: ion_step=10


... I'm open to a discussion about rationale...


Paul


________________________________

**Comment by lcarasik** [comment]
> That would be possible, if we had an agreed upon interface/use-model.
> 
> I like the model of the preceding email --- verbose at the beginning, barely verbose once things are cruising along.

> I wouldn't know how to prescribe that in the .par file --- but I guess we could do something like:
> io_on:  istep < 100
> io_on: ion_step=10

I like the thought of this proposed model being one of the loglevel options in the .par or through the .rea file. I think having multiple models would be a useful feature depending on a user's needs. Other instances would be what is currently implemented through the loglevel functionality (though I haven't looked in the code yet to see what the different levels explicitly do outside of my quick testing of it). 

I've never actually realized the value of this till recently. I've been doing a bit of RANS simulations using the reg k-omega model and I'm finding the logfiles get way too large with the default logfile output.

**Comment by yslan** [comment]
May I ask what happens to the iocomm?
I try it with plan4 (also reg k-w), but that doesn't seem to reduce the print.

**Comment by fischer1** [comment]
iocomm used to control things like whether iteration histories get printed.


It's not very effective in the current code.


Paul


________________________________
