### ISSUE TITLE
lelr = lelg?

### ISSUE THREAD

**Issue by dshaver14** [Nek5000/Nek5000#636]
It seems the default size of lelr needs to be set to lelg if restarting from only 1 restart file.  Is this how it should behave?  If so, the SIZE template should be updated to reflect this behavior.

**Comment by stgeke** [comment]
This is only true for multi file io. In this lelr needs to be set to nelg/nfiles. Using nfiles=1 doesn’t make sense to me? Any reason not to use MPIIO for this case?

On 29 Jul 2019, at 19:41, Dillon Shaver <notifications@github.com <mailto:notifications@github.com> > wrote:

It seems the default size of lelr needs to be set to lelg if restarting from only 1 restart file. Is this how it should behave? If so, the SIZE template should be updated to reflect this behavior.

**Comment by dshaver14** [comment]
I think I understand now.  I guess a better fix would be to change the advice in the error message to set 'writeNfiles = lpmin'  in the par file, rather than "ERROR: increase lelr in SIZE to        $lelg"

**Comment by stgeke** [comment]
Typically it not a good idea to use writeNfiles = lpmin!

-----Original message-----

**Comment by fischer1** [comment]
All in all, lelr is causing grief for a lot of people... I'll try to understand this discourse shortly (on a call)

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/08e8e6672ccf5e682c815343c827ed31f13a7dbf
