### ISSUE TITLE
Compilation Error in Ubuntu 18.04 + Clang

### ISSUE THREAD

**Issue by jeremylt** [Nek5000/Nek5000#645]
I'm trying to switch libCEED's Travis CI over to Ubuntu 18.04' but I'm hitting a strange error when I try to build the libCEED + Nek examples on Travis.

I'm getting a bunch of linker errors against `libnek5000.a` that recommend `recompile with -fPIC`, but adding this flag to `FFLAGS` does not fix the issue. Does anyone have any thoughts on a solution?

Sample errors
```
building libnek5000.a ... ar: `u' modifier ignored since `D' is the default (see `U')

done

gfortran  -O2 -g -std=legacy -I/home/travis/build/CEED/libCEED/include -DEXAMPLE_DIR='"/home/travis/build/CEED/libCEED/examples/nek/"' -cpp -fdefault-real-8 -fdefault-double-8 -std=legacy -g -std=legacy -I/home/travis/build/CEED/libCEED/include -DEXAMPLE_DIR='"/home/travis/build/CEED/libCEED/examples/nek/"' -DNOMPIIO -DUNDERSCORE -DGLOBAL_LONG_LONG -DTIMER -I/home/travis/build/CEED/libCEED/examples/nek/build -I/home/travis/build/CEED/libCEED/Nek5000/core -I./ -I /home/travis/build/CEED/libCEED/Nek5000/core/experimental -o nek5000 /home/travis/build/CEED/libCEED/Nek5000/core/drive.f /home/travis/build/CEED/libCEED/examples/nek/build/bps.o libnek5000.a -g -L/home/travis/build/CEED/libCEED/lib -Wl,-rpath,/home/travis/build/CEED/libCEED/lib -lceed -fPIC -L/home/travis/build/CEED/libCEED/Nek5000/3rd_party/blasLapack -lblasLapack -L/home/travis/build/CEED/libCEED/Nek5000/3rd_party/gslib/lib -lgs -Wl,--allow-multiple-definition

/usr/bin/ld: libnek5000.a(byte.o): relocation R_X86_64_32 against `.rodata.str1.16' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libnek5000.a(finiparser.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libnek5000.a(iniparser.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libnek5000.a(dictionary.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
...
```

CI run with full text of errors: https://travis-ci.org/CEED/libCEED/jobs/634419180?utm_medium=notification&utm_source=github_status

**Comment by stgeke** [comment]
It looks like you’re trying to link a position dependent library while generating a position independent executable. I can think of two options:

* compile with -fPIC instead of using it just for linking
* compile with -no-pie

**Comment by jeremylt** [comment]
I was compiling with `-fPIC`, but when our Nek script was built, we did not have CFLAGS. Clang 7.0.0 on Travis Xenial does not require the C portions of Nek to be built with `-fPIC` but Clang 7.0.0 on Travis Bionic does require the C portions of Nek to be built with `-fPIC`. Strange.

Thanks
