### ISSUE TITLE
New User for NEK5000

### ISSUE THREAD

**Issue by Abuhegazy** [Nek5000/Nek5000#647]
Hi all,
I just started reading about NEK5000 to use it in running simulations. I have some experience in coding and CFD, but I need to know more about the input and outputs of the code.

Could you please guide me the best way to start and getting familiar with the code so I will be able to modify the code for certain cases.

Thank you.

**Comment by stgeke** [comment]
http://nek5000.github.io/NekDoc/

**Comment by stgeke** [comment]
Please use our mailing list (see our homepage) for request like this.
