### ISSUE TITLE
Possible bug in hpts

### ISSUE THREAD

**Issue by juanecopro** [Nek5000/Nek5000#648]
Hello,

I think there could be a bug in this line of the code: https://github.com/Nek5000/Nek5000/blob/de16385b014ce0865a79199d967545ebd2129954/core/postpro.f#L1585

It should be "do i = 1,ldimt-1". I don't know if it's important but it would be good to check.

Thanks,
JuanDiego

**Comment by stgeke** [comment]
This is not a bug.
