### ISSUE TITLE
Issue of Nek5000 Installation using PGI compiler

### ISSUE THREAD

**Issue by evanyzk** [Nek5000/Nek5000#656]
### Hello, I am receiving error like below when I try to install  Nek5000 using PGI compiler with the command ''makenek eddy_uv''.  It seems the PGI Fortran was not properly installed or the path to it was not set up correctly. Can anyone assist me to solve this, please? Thank you

 "_pgf90io_sc_i_fmt_write", referenced from:
      _xerbla_ in libblasLapack.a(xerbla.o)
      _dlamc2_ in libblasLapack.a(dlamch.o)
  "_pgf90io_src_info03a", referenced from:
      _xerbla_ in libblasLapack.a(xerbla.o)
      _dlamc2_ in libblasLapack.a(dlamch.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [nek5000] Error 1

**Comment by yslan** [comment]
Hi @evanyzk,

Have you check FC and CC compiler (in ./makenek) is available in your system?

BTW, there is an user forum to discuss non-debug issue:
  https://groups.google.com/forum/#!forum/nek5000

**Comment by evanyzk** [comment]
Hi Yu-Hsiang,


Thanks for replying. Can you explain more about how to check the FC and CC compiler. BTW, I'm using a Mac version.


Sincerely,
Evan




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yu-Hsiang Lan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 凌晨1:24
收件人:&nbsp;"Nek5000/Nek5000"<Nek5000@noreply.github.com&gt;;
抄送:&nbsp;"setsuna"<1964228117@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Nek5000/Nek5000] Issue of Nek5000 Installation using PGI compiler (#656)





 
Hi @evanyzk,
 
Have you check FC and CC compiler (in ./makenek) is available in your system?
 
BTW, there is an user forum to discuss non-debug issue:
 https://groups.google.com/forum/#!forum/nek5000

**Comment by yslan** [comment]
If you look into makenek, you will find it calls CC=mpicc and FC=mpif77 by default.
So, you need to make sure the setup for your mpich or openmpi is correct corresponding to the PGI compiler you use.

Second thought, I think what the error message tells is you don't have lapack in your system?

**Comment by evanyzk** [comment]
Thanks for explaining, but I'm very new to this so I may not fully understand.I'm sure I already installed mpich. I know directory for that. Should I add any path about mpich in my terminal ? Should I download lapack to system also ?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yu-Hsiang Lan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 凌晨3:29
收件人:&nbsp;"Nek5000/Nek5000"<Nek5000@noreply.github.com&gt;;
抄送:&nbsp;"setsuna"<1964228117@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Nek5000/Nek5000] Issue of Nek5000 Installation using PGI compiler (#656)





 
If you look into makenek, you will find it calls CC=mpicc and FC=mpif77 by default.
 So, you need to make sure the setup for your mpich or openmpi is correct corresponding the PGI compiler you use.
 
Second though, I think what the error message tells is you don't have lapack in your system?

**Comment by stgeke** [comment]
Please use our mailing list for request like this.
