### ISSUE TITLE
MPI_Comm_get_attr not guaranteed for sub-communicators

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#662]
While debugging an app coupled to Nek5000 (through NekRS), we discovered that `MPI_Comm_get_attr` is not guaranteed to get pre-defined attributes for sub-communicators.  This is relevant in `setupcomm` where `MPI_TAG_UB` is queried:

``` Fortran
      ! check upper tag size limit
      call mpi_comm_get_attr(nekcomm,MPI_TAG_UB,ntags,flag,ierr)
      if (ntags .lt. np_global) then
         if(nid_global.eq.0) write(6,*) 'ABORT: MPI_TAG_UB too small!'
         call exitt
      endif
```

If `nekcomm` is a subcommunicator, this is not guaranteed to work.  In fact, GCC MPI on Summit fails to query `MPI_TAG_UB` on a sub-communicator.  

@emerzari pointed out that this could cause trouble for nek-nek.  

References:
* https://users.open-mpi.narkive.com/y8pGjDa3/ompi-users-mpi-comm-get-attr-fails-for-sub-communicators-created-by-mpi-comm-split 
* https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node210.htm#Node210

**Comment by stgeke** [comment]
I think we can just use MPI_COMM_WORLD for this check. Do you mind creating a PR for this?
