### ISSUE TITLE
Problem with maketools

### ISSUE THREAD

**Issue by brathod2** [Nek5000/Nek5000#663]
I am new to programming and thus know very little about it. I am trying to run NEK5000 on Ubuntu installed on Windows. 

Foremost, I fetched the gfortran compiler by ' sudo apt install gfortran'

Then after going to the tools directory I ran the command ' ./maketools all ' which gave the following error.

![image](https://user-images.githubusercontent.com/66644819/84075592-699e4e80-a9a2-11ea-8291-7167c38cd87c.png)

![image](https://user-images.githubusercontent.com/66644819/84075779-b4b86180-a9a2-11ea-9871-00201d560438.png)

I would be grateful for any help in this regard on how to properly build NEK5000.

**Comment by lcarasik** [comment]
Please check the user forum here (https://groups.google.com/forum/#!forum/nek5000) and user guide here (http://nek5000.github.io/NekDoc/quickstart.html)  for specific help. 

This has been asked before, so please spent a bit of time looking for the solution.

**Comment by brathod2** [comment]
Will do that. Thanks.
