### ISSUE TITLE
termination of makenek 

### ISSUE THREAD

**Issue by brathod2** [Nek5000/Nek5000#666]
![NekRS issue](https://user-images.githubusercontent.com/66644819/84977266-edb9aa00-b0f7-11ea-939d-052a3b176e28.PNG)
![Nek5000 issue](https://user-images.githubusercontent.com/66644819/84977267-edb9aa00-b0f7-11ea-8fec-c8905d895691.PNG)

I am trying to run Nek5000 as well as NekRS on a High Performance Computing server and am facing the following errors.

To set-up the environment I am doing the following:
bash
module load cmake
module load openmpi-gcc/openmpi4.0.0-gcc4.8.5
module load gcc/6.2.0
module load cuda/7.5

I would be grateful for any help. Thanks.

**Comment by stgeke** [comment]
Please use the nekRS repo.
