### ISSUE TITLE
github.com/LLNL/hypre repo not available

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/Nek5000#668]
Our HYPRE install script dowloads hypre from https://github.com/LLNL/hypre (see below).  However, it looks like that link is dead right now.  Not sure if this is a momentary problem, or if LLNL decided to move that repo.  

https://github.com/Nek5000/Nek5000/blob/47a7ce1d1f53502e9d96f68d5c288dac0b5e564e/3rd_party/hypre/install#L16-L24

**Comment by RonRahaman** [comment]
I noticed that NekRS gets HYPRE from a different repo, https://github.com/hypre-space/hypre .  

https://github.com/Nek5000/nekRS/blob/ea67c182889899fde55b306f4704b1c1c8741cf4/3rd_party/3rd_party.version#L23

Should Nek5000 get HYPRE from that repo, instead?

**Comment by stgeke** [comment]
Yes!

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/96a2b5e7909bf436fdf15aededb72e3a3b67ef3b
