### ISSUE TITLE
Support for 3d Conjugate Heat Transfer

### ISSUE THREAD

**Issue by SourangshuGhosh** [Nek5000/Nek5000#678]
Respected Sir,
I tried to run a 3d Conjugate Heat transfer in Nek5000. But it's failing to do so

**Comment by lcarasik** [comment]
Hi for questions such as this please sign up for and post it on the mailing list here:
 https://groups.google.com/g/nek5000

Also, if you ask questions, please be more specific in your case set up (velocity, temperatures, fluids, solids), what specifically is going wrong?

Github issues for Nek5000 are intended for specific code problems as opposed to likely user case set up issues.
