### ISSUE TITLE
gen_re2 segmentation violation error

### ISSUE THREAD

**Issue by yslan** [Nek5000/Nek5000#709]
This is observed at large case, says E>1M, which shows the following error after `call gen_re2(1)`
```Signal received: SIGSEGV - Segmentation violation```

After putting print statements inside gen_re2, I suspect the location is inside `gen_re2_bc`.
The `gen_re2_xyz` is ok. I can read the coordinated from a "partial complete" re2 file.

**Comment by yslan** [comment]
Update: found two relative small cases for debugging:
case 1: E=119352, success
```
 done genre2 (xyz only)
 gen_re2 header done
 gen_re2 xyz done
 gen_re2 curve done
 gen_re2 bc done 1
 gen_re2 bc done 2
 done genre2
```

case 2: E=177556, failed
```
 done genre2 (xyz only)
 gen_re2 header done
 gen_re2 xyz done
 gen_re2 curve done

  Signal received: SIGSEGV - Segmentation violation
```

**Comment by stgeke** [comment]
Can you please try to nail down what's causing it in gen_re2_bc.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/88f9517fde706f16e14ade34a7fd67cd5e94184c
