### ISSUE TITLE
Duplicate calls of geom_reset

### ISSUE THREAD

**Issue by yslan** [Nek5000/Nek5000#712]
In `nek_init` (drive1.f), we call

https://github.com/Nek5000/Nek5000/blob/221fa825431107f135cf1c2ea2ea6030d73cc401/core/drive1.f#L98-L99

However, `geom_reset(1)` is already called at the last line of the subroutine `fix_geom`.
This seems to be redundant? 

https://github.com/Nek5000/Nek5000/blob/221fa825431107f135cf1c2ea2ea6030d73cc401/core/navier5.f#L2416

**Comment by stgeke** [comment]
Agreed. Please issue a PR.
