### ISSUE TITLE
Bug in subroutine ZWGJ in speclib.f

### ISSUE THREAD

**Issue by timofeymukha** [Nek5000/Nek5000#714]
Please consider line 135 in speclib.f
`REAL*8  ZD(lzd),WD(lzd),APHAD,BETAD`

Note that `APHAD` is defined, whereas the intention is to define `ALPHAD`. As a result, `ALPHAD` is defined implicitly as a `real*4`, and not `real*8` as intended. While there is unlikely to be any affect on the computation, the intention of the code is clear, and the typo should be fixed.

**Comment by stgeke** [comment]
Not really an issue as we cast REAL->REAL8. However for cosmetic reasons we should fix it. Can you please issue a PR for this?

**Comment by timofeymukha** [comment]
OK
