### ISSUE TITLE
gmsh2nek: find hex face for quad id

### ISSUE THREAD

**Issue by GZC-lab** [Nek5000/Nek5000#732]
When I use 'gmsh2nek' to convert irregular hexahedron that uses Delaunay 3D algorithm in Gmsh. There is an error showing:

ERROR: cannot find hex face for quad 295
ERROR: this should not happen, please check your mesh
ERROR: or your mesh exporting process in gmsh

This error is caused by the 'irregular' hexahedron. The mesh screenshot is attached to the below website. 
Would anyone provide some suggestions? Thanks in advance!

![mesh](https://user-images.githubusercontent.com/77665740/122889833-b9fe0980-d375-11eb-8ec8-95d9269db73f.png)

**Comment by SIMONKUMOAR** [comment]
should define "physical volume"

**Comment by stgeke** [comment]
Is this a bug or a feature request? For questions, please use the mailing list.

**Comment by SIMONKUMOAR** [comment]
It is a question, but I have solved it now by setting in Gmsh. 

What is the mailing list? Next time I will use the list.
