### ISSUE TITLE
Allow longer "prefix" for writeFld

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/Nek5000#738]
The three-character limit for the prefix to the `writeFld` routine can be limiting and obscure the meaning of output files. It would be nice to increase this limit to a larger number of characters.

**Comment by stgeke** [comment]
I am closing this PR as writeFld() is a nekRS function. Can you please open a new PR to the nekRS repo.

**Comment by aprilnovak** [comment]
I thought the issue lay in the Nek5000 backend though? That's not the case? @yslan's suggested fixes on Slack were all in Nek5000

**Comment by stgeke** [comment]
I consider this a feature request for writeFld which belongs to nekRS. What's needed to implement this is a different story.

**Comment by aprilnovak** [comment]
IMO this belongs on the Nek5000 issues if the change should go into Nek5000 and the feature would affect Nek5000. But I've made an issue on NekRS as requested. If the issue is wording `writeFld`, I don't know the name of the actual underlying Nek5000 function that is called.
