### ISSUE TITLE
Advection switch for scalars missing

### ISSUE THREAD

**Issue by fTheobald** [Nek5000/Nek5000#742]
In reader_par.f (lines 731 to 738) there is a code snippet allowing to switch off/on advection for scalars. However in PARDICT the key is missing and therefore solver complains about unknown key. At a first glance it seems adding "     &  pardictkey(104) / 'SCALAR%%:ADVECTION' /" and changing "PARDICT_NKEYS" from 103 to 104 resolves the issue.

**Comment by stgeke** [comment]
Would you mind adding a pull request for that.

**Comment by fTheobald** [comment]
I created a pull request. However never done a pull request before, so I hope the way I have done it is alright.
