### ISSUE TITLE
[prenek] no gui mode

### ISSUE THREAD

**Issue by yslan** [Nek5000/Nek5000#746]
It will be nice if we can have a mode that doesn't require a display so we can run some big mesh actions on server.

`GUI=0 pretex`

**Comment by fischer1** [comment]
pretex?

**Comment by fischer1** [comment]
Oh... I see.

Would you want to look into how to do that?

**Comment by lcarasik** [comment]
This would also be very useful for my fledging group of nek users.

**Comment by stgeke** [comment]
No code changes are required for this. Just use https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml

**Comment by yslan** [comment]
In case someone is still searching, this can be done by
```
xvfb-run pretex << EOF

... some pretex script

EOF
```
