### ISSUE TITLE
maketools genmap 

### ISSUE THREAD

**Issue by nogot404** [Nek5000/Nek5000#756]
Hi! I am attempting to install Nek5000 but the installation fails at the stage of ./maketools genmap. As a result, I get "building genmap ... failed" and no other clarification on error. Has it ever occurred to anyone? 

Cheers,
Ana

**Comment by stgeke** [comment]
Please use the mailing list for request like this.

**Comment by hashthug-create** [comment]
I also have same issue if someone can help will be much appreciated . Also new to Linux in general
