### ISSUE TITLE
RANS - turbulence

### ISSUE THREAD

**Issue by gnastro** [Nek5000/Nek5000#760]
Hi Neks,

I am simulating flows around a NACA airfoil at Re=10^4/10^6 using the rans_komg.f module from Nek5000 (the latest updated version as reported in the article by Tomboulides et al. Int. J. Heat Fluid Flow 2018). In this regard I have two questions to ask. 
The first issue is that when I switch from 2D to 3D with a mesh already used for a DNS, the code after passing inside the fix_geom subroutine reduces my domain in the spanwise direction z. To be precise, the domain in z is equal to one chord (L_z = 1), but "suddenly" it becomes 0.75 with zmin = 0.125 and zmax = 0.875 (while they should be 0 and 1, respectively). Look at the logfile excerpt below ( I have inserted some CHECKS in fix_geom):

...
ywmin and yw  0.6509446E-02 0.6493389E-02  2.000000        8    5    894904
 xmin =   -19.0000000000000
 xmax =    40.0000000000000
 ymin =   -20.0000000000000
 ymax =    20.0000000000000
 zmin =   0.000000000000000E+000
 zmax =    1.00000000000000
 CHECK 01
 xmin =   -19.0000000000000
 xmax =    40.0000000000000
 ymin =   -20.0000000000000
 ymax =    20.0000000000000
 zmin =   0.000000000000000E+000
 zmax =    1.00000000000000
 CHECK 02
 xmin =   -19.0000000000000
 xmax =    40.0000000000000
 ymin =   -20.0000000000000
 ymax =    20.0000000000000
 zmin =   0.125000000000000
 zmax =   0.875000000000000
  7.1054E-15  3.5527E-15  5.0000E-01  7.1054E-15  3.5527E-15  5.0000E-01 xyz repair 1
...

After this, the code gives NaNs (see below...) 

...
Dealiasing enabled, nxd=          12

 Estimated eigenvalues
 EIGAA =    5.85165572031620
 EIGGA =                      NaN
 EIGAE =   2.835278483507428E-003
 EIGAS =   4.037715447589336E-005
 EIGGE =                      NaN
 EIGGS =    2.00000000000000
...

The second problem (more methodological/conceptual) is that the code (for the 2D case, the 3D case does not work as said before) with any turbulence model (in general, uRANS k-omega) provides for long times a steady state even for relatively high angles of attack (alpha=12° and Re=10^6). Which is very strange since I expect at least a global von Kármán-type oscillation.

Thank you in advance for your help.

Best regards,
Gabriele

**Comment by stgeke** [comment]
Please use our mailing list for request like this.
