### ISSUE TITLE
user sections in runtime parameters

### ISSUE THREAD

**Issue by adampep** [Nek5000/Nek5000#78]
It is continuation of discussion abut user space in the new runtime parameters scheme we had at user meeting. Right now there are a number of "userparam" in "general" section, but for toolboxes it would be good to have separate user sections as well. With Stefan we've concluded that it would be enough to modify slightly parameter check, so sections starting with 'U' would be skipped, and keeping dictionary available for user during whole simulation (moving finiparser_free to nek_end).

**Comment by stgeke** [comment]
Done, see #86

**Comment by adampep** [comment]
Perfect. Thank you
