### ISSUE TITLE
error on nekbmpi

### ISSUE THREAD

**Issue by woiiiiow** [Nek5000/Nek5000#788]
I was running the case in tutorial [Fully Developed Laminar Flow](http://nek5000.github.io/NekDoc/tutorials/fdlf.html#), and the nekbmpi went wrong like below,

> juchen@gargamel:~/SSD2/Nek5000/run/fdlf$ nekbmpi fdlf 4
> juchen@gargamel:~/SSD2/Nek5000/run/fdlf$ No protocol specified

How to fix it?

**Comment by yslan** [comment]
nekbmpi sends job into background. So, can you verify whether the job run? did it generate a logfile? 

As for the warning message, it seem to be a hwloc issue. This might help.
```
export HWLOC_COMPONENTS=-gl
```

ref:
https://github.com/open-mpi/ompi/issues/7701
https://github.com/open-mpi/hwloc/issues/483

**Comment by woiiiiow** [comment]
thanks, it works

**Comment by stgeke** [comment]
Please use the mailing list for request like this.
