### ISSUE TITLE
Working directory changed: can break extension code and .usr code

### ISSUE THREAD

**Issue by paugier** [Nek5000/Nek5000#792]
Last commit in master (https://github.com/Nek5000/Nek5000/commit/30f06bc533d957397dbe069d4d419d66c4711bfb) which was introduced directly on master without PR and without mentioned issue changed a lot the behavior of Nek5000.

With this last commit, the working directory is now the session directory. This changes the directory where files mentioned with relative paths are saved.

This can affect extensions and .usr code where relative paths can be used. This also breaks Snek5000 (see https://github.com/snek5000/snek5000/issues/270 and https://github.com/snek5000/snek5000-cbox/pull/52).

Is this change of working directory really useful? If yes, I guess it should be documented.

Note: with Snek5000, we assumed that Nek5000 is run from the case directory and we have `SESSION.NAME` files with things like

```
cbox
./session_00
```

**Comment by stgeke** [comment]
We document all relevant changes in the release notes. However, no updated notes are available because there is no new release.
