### ISSUE TITLE
ioinfo not working

### ISSUE THREAD

**Issue by cfrouzak** [Nek5000/Nek5000#806]
In the latest comm_mpi.f, the path is blanked out:

 128       !path = path_mult(idsess)
 129       call blank(path,len(path))

and the content of the ioinfo file in subroutine check_ioinfo (prepost.f)  is not checked.

Should it be changed to:

 128       path = path_mult(idsess)
 129       !call blank(path,len(path))

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/354d9824f5a39bd7e1d3906a31eb4f8260a5a9e3
