### ISSUE TITLE
missing rans_wallfunctions.f file

### ISSUE THREAD

**Issue by rajamunr** [Nek5000/Nek5000#808]
I was trying to go through the RNS Channel and Multi-Component RANS tutorials and when making these cases I get the error message, Error: Can't open included file 'experimental/rans_wallfunctions.f'.

I looked at NEK5000/core/experimental folder and the rans_wallfunctions.f file was missing. It was not there in GitHub either.

**Comment by dshaver14** [comment]
@rajamunr , where did you get your rans_komg.f file and case setup from? The rans_wallfunctions.f file is part of a future WIP update that hasn't been released yet.
