### ISSUE TITLE
ERROR: Error opening file in mfo_open_files.   ierr=***

### ISSUE THREAD

**Issue by ajariwala611** [Nek5000/Nek5000#817]
Hello,

I am a graduate student at UT Austin and I am using NEK5000 for my research. I am running into this 'ERROR: Error opening file in mfo_open_files.   ierr=***'. I have tried to find the underlying cause of this but have had no luck. This error message appears randomly while the simulation is running and stops the run. There is no common trend. I am attaching my *.usr and logfiles. Could you please help me fix this issue or probable underlying bug with I/O? 
[flat_plate.zip](https://github.com/Nek5000/Nek5000/files/12443354/flat_plate.zip)

**Comment by fischer1** [comment]
Dear Akshit,

It crashed while trying to open a file to write output.
Unlikely that it is a random nek issue, but rather something
to do with your filesystem (e.g., not enough space or unavailability
of the io system for some other reason).

How full is the scratch space where it's trying to open the output file?

hth,

Paul

________________________________
From: Akshit Jariwala ***@***.***>
Sent: Friday, August 25, 2023 3:35 PM
To: Nek5000/Nek5000 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Nek5000/Nek5000] ERROR: Error opening file in mfo_open_files. ierr=*** (Issue #817)


Hello,

I am a graduate student at UT Austin and I am using NEK5000 for my research. I am running into this 'ERROR: Error opening file in mfo_open_files. ierr=***'. I have tried to find the underlying cause of this but have had no luck. This error message appears randomly while the simulation is running and stops the run. There is no common trend. I am attaching my *.usr and logfiles. Could you please help me fix this issue or probable underlying bug with I/O?
flat_plate.zip<https://urldefense.com/v3/__https://github.com/Nek5000/Nek5000/files/12443354/flat_plate.zip__;!!DZ3fjg!6KKb6NlqJxw_aSO6VGKmmfJQxnCnGC9xuRzRMVPI33w1YI0QruqwFhaoj1W-HszcitHhW1sMIt9u1oP6vrgZgALN5qw$>

**Comment by ajariwala611** [comment]
Dr. Fischer,

Thank you so much for your response. I will ask our HPC admins to figure out if the issue is with underlying filesystems. Usually, the scratch file system does not have space availability issues. I have another TBL simulation running which works fine and has never crashed. And also the *.f000 file is significantly small (~500MB) compared to the available space on scratch.  Please let me know if I should look at something else. I appreciate your help.

**Comment by stgeke** [comment]
Please use the mailing list for discussion like this.
