### ISSUE TITLE
gmsh2nek failed to work with genmap, created broken .re2 file

### ISSUE THREAD

**Issue by FanruiC** [Nek5000/Nek5000#819]
- gmsh2nek and genmap both can be compiled without error. 
- gmsh2nek can create .re2 file successfully.
_**- genmap cannot work with the above .re2 file.**_

- Temporary solution: using prvious version of gmsh2nek, then genmap can work with .re2 successfully.

**Comment by yslan** [comment]
I guess after this change, https://github.com/Nek5000/Nek5000/pull/818, we need genmap to support v04 format.

**Comment by stgeke** [comment]
https://github.com/Nek5000/Nek5000/commit/57abc6c60a4ed23dbd2463786cf9ee6bbcd7ecae should fix it?
