### ISSUE TITLE
DOFs assembly (gathering) on GPU  ?

### ISSUE THREAD

**Issue by Marshdweller** [Nek5000/Nek5000#832]
Hi everyone,

I have been studying the GPU kernels of Nek for elliptic equations, specifically focusing on the axhelm kernel. From my understanding, the matrix-vector multiplication is performed on the separated degrees of freedom (DOFs) per element. There should be an assembly ("gathering") phase where duplicated DOFs are accumulated into physical DOFs. I believe you call it "gather-scatter operator". 

I have been unable to locate where this gathering and scattering occur in the GPU code. Could someone please point me in the right direction?

Thank you!

**Comment by yslan** [comment]
This seems to be a NekRS question. I suggest to ask it [there](https://github.com/Nek5000/nekRS/discussions)
See the oogs in the [code](https://github.com/Nek5000/nekRS/blob/master/src/solvers/elliptic/ellipticOperator.cpp)

Unless, you are looking into the OpenACC branch of Nek5000...

**Comment by Marshdweller** [comment]
Thank you @yslan . Yes, it is `oogs` , will check it out
