### ISSUE TITLE
unknown jey GENERAL:CONSTFLOWRATE

### ISSUE THREAD

**Issue by DiegoBindoni** [Nek5000/Nek5000#840]

**Comment by DiegoBindoni** [comment]
Good morning, i've tried to run the hill periodic case from the tutorial sections, but after following the steps the logfile reports this error

 Number of MPI ranks :           4
  
 Reading /home/diego/Nek5000/run/hillp/hillp.par                                                                                             
 ERROR: Par file contains unknown key GENERAL:CONSTFLOWRATE                                                                                                               
 ERROR: Par file contains unknown key GENERAL:MEANVELOCITY       
 
 I've also tried to simply use the input files provided, but it gives me always the same error.
 Could you please address me to the problem?
 Thanks in advance, and let me know how i can provide more information about the issue.
 Regards,

Diego Bindoni

**Comment by yslan** [comment]
What version of Nek5000 are you using?
Those par keys are added in this commit https://github.com/Nek5000/Nek5000/commit/2a39166a8ce64b74c2c626d68efd7fb828d8c564

**Comment by DiegoBindoni** [comment]
I'm currently using the last available version of Nek5000, hence v19.0

**Comment by DiegoBindoni** [comment]
I've checked also the par keys, and actually in my file there aren't these entries. It's enough to substitute with the new file and then recompile? Or maybe is better to redownload from git? I've downloaded the tar.gz file on the main website

**Comment by yslan** [comment]
You will need the latest git repo version, or at least after the commit 2a39166 to have those new keys. v19 is older than that

**Comment by DiegoBindoni** [comment]
ok thanks for the clarification! I will download the version from git. The one on the website, fyi, downloads the v19.0. Thanks for the help!
