### ISSUE TITLE
Running pretex on a server machine with no GUI

### ISSUE THREAD

**Issue by karim-manaouil** [Nek5000/Nek5000#841]
Hi!

I am trying to run this tutorial [1]. However, I can't seem to get the pretex tool working. I get the error

`Can't open display
Did you setenv DISPLAY to your localHost
and xhost + on the local display?`

Please note that this is a server machine with no GUI. It's just a powerful machine to run computation. I don't understand why a GUI is needed to run computation.

[1] https://nek5000.github.io/NekDoc/tutorials/conjht.html

**Comment by stgeke** [comment]
Please use the user group for request like this.
