### ISSUE TITLE
How to evaluate the surface integral in 3D, line integral in 2D 

### ISSUE THREAD

**Issue by Maccchiatooo** [Nek5000/Nek5000#843]
I am trying to evaluate the surface integral in 3D, or line integral in 2D. I find that `area(ix,iz,f,e)` is defined as the weight. However, I don't know how to then compute the summation after multiplying the area. Do we have to add them one by one for the whole element? Is there an easy way to directly compute the surface integral/ line integral?

**Comment by stgeke** [comment]
Please use the mailing list for things like this.
