### ISSUE TITLE
chkjac calls in coef.f

### ISSUE THREAD

**Issue by kmittal2** [Nek5000/Nek5000#85]
I think line 652 (and 539) of coef.f where chkjac routine is called, should be:
CHKJAC(JACM1(1,1,1,ie),NXYZ1,ie,xm1(1,1,1,ie),ym1(1,1,1,ie),zm1(1,1,1,ie),ndim,ierr) instead of 
CHKJAC(JACM1(1,1,1,ie),NXYZ1,ie,xm1,ym1,zm1,ndim,ierr)
because of how chkjac routine is written. This will help output the right xm1,ym1,zm1 values in-case there is an inverted element.

**Comment by stgeke** [comment]
Do you want to submit a PR for this otherwise I will close it.

**Comment by kmittal2** [comment]
Stefan,

I will submit the PR sometime this week.

Thanks,
Ketan

On Feb 11, 2017, at 11:44 AM, Stefan K. <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you want to submit a PR for this otherwise I will close it.

**Comment by stgeke** [comment]
#224
