### ISSUE TITLE
(linear) Adjoint equations for temperature

### ISSUE THREAD

**Issue by pschlatt1** [Nek5000/Nek5000#88]
extend the current linear adjoint for velocity with the respective terms in the temperature equation (with Boussinesq approximation). Question: Should we contribute that already for R16?

**Comment by stgeke** [comment]
Can somebody please update me on this otherwise I am closing this issue for now.

**Comment by pschlatt1** [comment]
yes, can be closed. The relevant code was in PR #141 and the corresponding example in #337.
