### ISSUE TITLE
Add inhomogeneous "O" condition ("o", "on")

### ISSUE THREAD

**Issue by pschlatt1** [Nek5000/Nek5000#89]
Add capability to have inhomogeneous stress conditions (i.e. setting the "ambient pressure" pa) also for no-stress PnPn-2. This essentially means to make sure that "o" works fine. Question: Should this be done for R16?

**Comment by oanaoana** [comment]
Yes we should do that. But I think maybe one should add the nozzle as well, and have an extensive treatment of Boundary Conditions, maybe convective too.

**Comment by pschlatt1** [comment]
The nozzle and convective conditions can be treated from the user file, whereas the "o" conditions require change in the core. Therefore I guess for that issue we can focus on "o", "on" etc. separately.

**Comment by fischer1** [comment]
Hi Philipp.  Have you guys tried/developed this capability already ?

**Comment by pschlatt1** [comment]
yes, we have, and we will commit a "fix" for that soon. Should this still be done for R16?

**Comment by pschlatt1** [comment]
fixed in #99 for PnPn-2.
